### PR TITLE
Use ScalaTest 3.0.8 so new JUnitSuite is available from Java

### PR DESCRIPTION
**Pull request by jlprat**
Trying the new RC from ScalaTest to see if Java code can see the new `JUnitSuite` class

### CODE REVIEW

**Comment by jlprat** [comment]
If I update to 3.0.8, I need to also update Scala Version to 2.13.0 (as it's published for the final version, not for RC) but then, travis fails when MiMa tries to get older versions of our modules:

```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.akka#akka-http-spray-json_2.13;10.0.2: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
....
[errorm] (akka-http-spray-json / mimaPreviousClassfiles) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.akka#akka-http-spray-json_2.13;10.0.2: not found
[error] (akka-http-xml / mimaPreviousClassfiles) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.akka#akka-http-xml_2.13;10.0.5: not found
[error] (akka-http-caching / mimaPreviousClassfiles) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.akka#akka-http-caching_2.13;10.1.2: not found
[error] (akka-http / mimaPreviousClassfiles) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.akka#akka-http_2.13;10.0.1: not found
[error] (akka-http-jackson / mimaPreviousClassfiles) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.akka#akka-http-jackson_2.13;10.0.9: not found
[error] (akka-http-core / mimaPreviousClassfiles) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.akka#akka-http-core_2.13;10.0.9: not found
[error] Total time: 145 s, completed Jun 12, 2019 8:26:13 AM
```

**Comment by raboof** [comment]
Sorry about that - that is fixed at https://github.com/akka/akka-http/pull/2568/files#diff-49b6a013884df4c1dc45bcf246a23b7aR66

**Comment by jlprat** [comment]
It can wait until that PR is merged then :smile:

**Comment by jlprat** [comment]
Ready to review 🙂

**Pull request merged**
