### PR TITLE
+ht2 #245 parse PriorityFrame but without rendering

### PR DESCRIPTION
**Pull request by gosubpl**
PriorityFrame HTTP2 model, without renderer atm

### CODE REVIEW

**Comment by gosubpl** [comment]
Refs #245

**Comment by gosubpl** [comment]
@jrudolph @ktoso please give me some guidance how to add remaining frame models. I have started with `PriorityFrame` in this PR. What is done - is parsing the frame. What is not done - is rendering the frame back. There is interesting comment: https://github.com/akka/akka-http/blob/master/akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameRenderer.scala#L31 
Does it mean that we are not aiming at rendering `PriorityFrames` atm or you think that this should be done in a separate renderer?

**Comment by ktoso** [comment]
AFAICS this is a good step anyway. 
As for rendering PRIORITY frames I don't think we'll support that in the first versions simply, so we don't need to care about rendering I think.

**Comment by gosubpl** [comment]
This just needs one more fix around the bit-twiddling

**Comment by ktoso** [comment]
LGTM from my side, thanks a lot :)

**Comment by jrudolph** [comment]
Thanks, @gosubpl.

**Comment by jrudolph** [comment]
I think adding rendering makes a lot of sense to allow testing of round trips which helps to find problems with edge cases. Apart from that more tests for parsing (for the edge conditions) would be nice as well.

**Comment by gosubpl** [comment]
Yup, I will get around to that. The priority thing should probably be consumed in the Demux and asynchronously change scheduler settings, is there any scaffolding for this to try looking into placing that logic somewhere?
Thanks @jrudolph !

**Pull request merged**
