### PR TITLE
#2279 Fix status code in case of EntityStreamSizeException

### PR DESCRIPTION
**Pull request by ashishkujoy**
#2279 Modify RejectionHandler to complete request which encounter EntityStreamSizeException with RequestEntityTooLarge status code instead of BadRequest

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @ashishkujoy,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ashishkujoy** [comment]
Hi I signed the CLA

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
(Let's mention #2279 in the comments because then github creates a link in both directions, having it in the PR title is not enough unfortunately)

**Pull request merged**
