### PR TITLE
Add reference to Content-Type of HTML forms (#331)

### PR DESCRIPTION
**Pull request by jlprat**
Issue: #331 
Add references to the possible Content-Type of the HTML Forms for all FormFieldDirectives.
Add reference as well on both directive indexes (alphabetical and by trait).
Additionally, fix missing "Description" header for formField page.

### CODE REVIEW

**Comment by jrudolph** [comment]
OK TO TEST

**Comment by jrudolph** [comment]
LGTM

**Comment by jrudolph** [comment]
Thanks, good addition. I guess it will help to find pages like this more easily.

**Comment by ktoso** [comment]
I've added you to our whitelist @jlprat :)

**Comment by ktoso** [comment]
PLS WHITELIST

**Comment by jrudolph** [comment]
Does "PLS WHITELIST" work?

**Comment by jrudolph** [comment]
Btw. I also added jlprat to the whitelist when I made my comment a few minutes ago.

**Comment by ktoso** [comment]
> Does "PLS WHITELIST" work?

I'm actually not sure, wanted to try, I see he was added before hm ;)

**Comment by jlprat** [comment]
Don't know if it's the right place, but jenkins job 304 has hung and it's running for almost an hour.
https://jenkins.akka.io:8498/job/pr-validator-akka-http/304/console

**Comment by ktoso** [comment]
Thanks for reporting, I killed it. It's weird... sometimes does that, need
to debug that finally

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 17 November 2016 at 11:48:17, Josep Prat (notifications@github.com)
wrote:

Don't know if it's the right place, but jenkins job 304 has hung and it's
running for almost an hour.
https://jenkins.akka.io:8498/job/pr-validator-akka-http/304/console

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-http/pull/538#issuecomment-261215604>, or mute
the thread

**Comment by jlprat** [comment]
So, if I understood right, after being whitelisted I could ask the akka-ci bot to test, right?

**Comment by ktoso** [comment]
Yeah, you should be able to say PLS BUILD etc from now on

**Comment by ktoso** [comment]
PLS BUILD

**Comment by jlprat** [comment]
OK TO TEST

**Comment by ktoso** [comment]
For reference:
OK TO TEST - only allows jenkins to pick up a change from a non-whitelisted person
PLS BUILD - actually asks jenkins to run a build (also when given commit was already tested)

**Comment by jlprat** [comment]
Sloppy fingers.... I clicked Close instead of comment....
Thanks for the info about the commands

**Comment by ktoso** [comment]
And we're green :) Thanks!

**Pull request merged**
