### PR TITLE
=doc Change marshallers to unmarshallers #1422

### PR DESCRIPTION
**Pull request by satansk**
Fix the typo.

### CODE REVIEW

**Comment by jlprat** [comment]
OK TO TEST

**Comment by jonas** [comment]
Note, this typo has been [fixed](https://github.com/akka/akka-http/pull/1388/files#diff-616f7cb6380ab96541f8bbeb9c50709dR27) in #1388 (Merge common/unmarshalling.md and improve the Java version).

**Comment by jlprat** [comment]
I completely forgot about those open merge tickets! I'll try to get some time and go over the pending ones! @jonas

**Comment by satansk** [comment]
oh @jboner I did not notice your PR 😭

**Comment by jonas** [comment]
My bad, I should nag people more to review my doc PRs. AFAIC, we can merge this and I'll rebase #1388 once it gets some feedback.

**Comment by satansk** [comment]
Thank you @jonas , and I'll pay more attention to the open PRs to avoid this again 😀

**Comment by jrudolph** [comment]
Refs #1422.

**Pull request merged**
