### PR TITLE
Some of Response code are not correct

### PR DESCRIPTION
**Pull request by SHUB9914**
I found error at some places like at  line number 28 , 31 , 34 ,  38 , 40 , 69 . which was because of not proper format of  HttpResponse , There should be the use of StatusCodes before defining any error and entity before defining message in HttpResponse , so I have corrected it  please check and confirm.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @SHUB9914,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
Hi, thanks for taking the time to get in touch about this. You modified the documentation and changed the 'shorthand' `complete()` notation to 'long form' notation in a couple of places.

I think it's not too bad to show both, did you have problems with the shorthand notation?

**Comment by SHUB9914** [comment]
Hi @raboof 
yes It's giving me error if I use this shorthand notation . That's why I updated it to the proper format. 
if you are passing only message in complete method than it's working fine , but if you are using some error with it than in that case you have to use StatusCodes for defining the error and the entity for the message , other wise  it will give an error .

**Comment by SHUB9914** [comment]
hi @lightbend-cla-validator 
I have successfully signed the CLA

**Comment by raboof** [comment]
Can you share which error you're getting? The examples in our documentation are also compiled so we're pretty confident they should work, so it should be interesting to learn why they don't work for you. Are you sure you have all the imports?

**Comment by SHUB9914** [comment]
Hi @raboof 
image


Here you can see the red line occurs when I did not use StatusCodes before error "NotFound" .

**Comment by raboof** [comment]
When using the shorthand notation you should not have `entity =` in there. Also, do you have an `import StatusCodes._` like in the documentation to bring `NotFound` into scope?

**Comment by SHUB9914** [comment]
hi @raboof 
as you told for using 
import StatusCodes._    and  you should not have entity = 
so I did it . but after that it's not working , you can see below  

image

**Comment by SHUB9914** [comment]
and if I am using StatusCodes then it's working , you can see below 
image

**Comment by jrudolph** [comment]
That's a bug in IntelliJ IDEA. Can make sure you run the latest version of IntelliJ IDEA and otherwise create an issue at their bug tracker at https://youtrack.jetbrains.com/issues/SCL

**Comment by raboof** [comment]
It seems you accidentally imported `org.omg.CosNaming.NamingContextPackage.NotFound`, removing that might also help?

**Comment by SHUB9914** [comment]
Hi @raboof 
Now it's working , it was not working because of  org.omg.CosNaming.NamingContextPackage.NotFound

**Comment by raboof** [comment]
@SHUB9914 that's great! I suppose there's not a lot we can do in the documentation to make this easier, so perhaps we should just close this PR?

**Comment by SHUB9914** [comment]
yes sure @raboof

**Comment by jonas** [comment]
Related with #486

**Pull request closed without merging**
