### PR TITLE
Http client decoding response example in docs  #685

### PR DESCRIPTION
**Pull request by emanresusername**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @emanresusername,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Would you be so kind to sign the SLA so we can merge? It is enough to confirm via the above site, via github that you've signed it. Thanks a lot!

**Comment by emanresusername** [comment]
i thought i did . . . but let me double check, the email in my `.gitconfig` might be different/not associated with github/etc

**Comment by ktoso** [comment]
Could be, thanks :) I'll check manually later then.
Ignore the test failure, it's a misconfiguration we need to fix.

**Comment by ktoso** [comment]
PLS BUILD ALL

**Comment by emanresusername** [comment]
👍 i resigned, and confirmed i have a couple `Typesafe CLA signed` emails in my inbox, can trouble shoot from there later if the manual check doesn't show the same

**Comment by jrudolph** [comment]
Thanks a lot, @emanresusername. I added a bit more text to the documentation paragraph.

**Comment by ktoso** [comment]
Resolved https://github.com/akka/akka-http/issues/760

**Pull request merged**
