### PR TITLE
core: add request timeout support to client-side pool APIs #42

### PR DESCRIPTION
**Pull request by rafal2nowak**
Reference [#42](https://github.com/akka/akka-http/issues/42)

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @rafal2nowak,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by rafal2nowak** [comment]
Hi,
I just signed the CLA.

**Review by jrudolph — COMMENTED** [review]
Thanks a lot @rafal2nowak at taking a stab at this.

I'm not yet convinced that this is the approach we want to take (which is also one reason we never went ahead and implemented something so far).

This kind of request-timeout only takes into account the time a request was handed to the pool until a response is dispatched back to the user.

What people often want instead is a full-roundtrip timeout from dispatching a request to the pool (via `Http.singleRequest`) until the response is dispatched back. The other really important feature is that requests that are already timed out are cancelled as soon as possible. This means that these kinds of requests should not be dispatched if they have timed out in the queue. We might also want to give the option to be even more aggressive and reset pool slots if a response does not arrive in time.

So I guess, we are a bit suffering from sacrificing the good for the perfect solution here but if we accept this as a preliminary solution we need to be sure that we don't spent the `request-timeout` setting in a way that would prevent us from making it more aggressive later on.

**Comment by rafal2nowak** [comment]
@jrudolph thank you for explanation. Given that I am closing this PR.

**Pull request closed without merging**
