### PR TITLE
Avoid updating whitesource-stable for 10.0 releases

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by jrudolph** [comment]
Seems PR validation does not yet work for the release-10.0 branch, could you look into that @raboof?

**Comment by jrudolph** [comment]
We can also merge here and ticketify the release-10.0 PR validation issue.

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
PLS BUILD

**Pull request merged**
