### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by stsatlantis**
one -> on fix

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @stsatlantis,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jlprat** [comment]
OK TO TEST

**Comment by jlprat** [comment]
PLS BUILD
The build hang

**Comment by jlprat** [comment]
Thanks for your contribution @stsatlantis !

**Pull request merged**
