### PR TITLE
=htc align logging in PoolConductor to other GraphStages (#482)

### PR DESCRIPTION
**Pull request by gosubpl**
Minor improvements to error logging output in PoolConductor bringing it in-line with other GraphStages

### CODE REVIEW

**Comment by gosubpl** [comment]
Refs https://github.com/akka/akka-http/issues/482

**Comment by gosubpl** [comment]
Refs https://github.com/akka/akka-http/issues/482

**Comment by gosubpl** [comment]
Refs https://github.com/akka/akka-http/issues/482

**Comment by gosubpl** [comment]
Hmm... at least once delivery in action :)

**Comment by 2beaucoup** [comment]
I quick search for `Inlet()`/`Outlet()` usages reveals that we don't really have a naming standard for the ports (yet).

**Comment by ktoso** [comment]
We do, though it seems violated in places.
The standard is `val someInput == "MyClass.someInput"`

**Comment by 2beaucoup** [comment]
We defer from that in about 50%.

No mandatory "in"/"out" suffix in variable names?

@gosubpl Any chance of going all the way on this one?

**Comment by gosubpl** [comment]
@2beaucoup I would be more than happy. Let's agree the standard and then I will grep the project to change to what was agreed. OK?

**Comment by 2beaucoup** [comment]
```scala
val thingIn = Inlet[ThingClass]("MyClass.thingIn")
val thingOut = Outlet[ThingClass]("MyClass.thingOut")
```
?

**Comment by ktoso** [comment]
The above sounds good.

> No mandatory "in"/"out" suffix in variable names?

I don't think those are mandatory, but very often are a good default to add.

**Comment by jrudolph** [comment]
LGTM. Thanks for splitting it out, @gosubpl. Could you change to `SlotSelector.slotEventIn`, etc.?

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by ktoso** [comment]
I adjusted the names, merging - thanks a lot @gosubpl !

**Pull request merged**
