### PR TITLE
http2: use scheme portion of target URI in :scheme pseudo-header

### PR DESCRIPTION
**Pull request by raboof**
https://tools.ietf.org/html/rfc7540#section-8.1.2.3

Tests for this are already in #3532

### CODE REVIEW

**Review by jrudolph — APPROVED** [review]
Not sure the mentioned proxy use cases in the spec are relevant but I'm still fine with that change as it probably won't change anything in the common case.

**Comment by jrudolph** [comment]
> Tests for this are already in #3532

Yes, but they are now failing, is that what you meant?

**Comment by jrudolph** [comment]
> > Tests for this are already in #3532
> 
> Yes, but they are now failing, is that what you meant?

Fixed in https://github.com/akka/akka-http/pull/3526/commits/8edcd7cd82b281a5fbd2b1a1d05bbe687180d944

**Comment by raboof** [comment]
> > Tests for this are already in #3532
> 
> Yes, but they are now failing, is that what you meant?

Yes, thanks for fixing :D

**Pull request merged**
