### PR TITLE
build: also aggregate akka-http-bench-jmh to fail if benchs fail to compile

### PR DESCRIPTION
**Pull request by jrudolph**

### CODE REVIEW

**Comment by jrudolph** [comment]
Should fail until based on #3559

**Comment by jrudolph** [comment]
Ok, didn't fail because I already merged the fixed :roll_eyes:

**Review by raboof — APPROVED** [review]
weird that they weren't there before :+1:

**Comment by jrudolph** [comment]
The first benchmark and the module was contributed, so maybe we just missed it in the review.

**Pull request merged**
