### PR TITLE
Fix HeaderParser Unicode issue

### PR DESCRIPTION
**Pull request by jrudolph**
Seems to be a byte->char conversion problem. Since someone finally provided a reproducible test case, I had a quick look. Still needs proper tests.

Refs #1484

### CODE REVIEW

**Comment by jrudolph** [comment]
Now added a proper (but very simple) test.

The reason it was so elusive is that it was related to caching. So, to trigger it, there have to be two subsequent headers lines where the second one is a prefix of the first one up to the non-ascii char in the first line. Since caching is done on a per-connection base, those headers could be requests / responses apart.

In the example that @shkhln provided it was a single multipart file upload request with two files that both started with a non-ascii character. In that case the resulting `Content-Disposition` lines of the two body parts shared a prefix up to the filename where it crashed on the occurrence of the second one...:

```
0000: POST /upload HTTP/1.1
0017: Host: 127.0.0.1:8080
002d: User-Agent: curl/7.65.3
0046: Accept: */*
0053: Content-Length: 342
0068: Content-Type: multipart/form-data; boundary=--------------------
00a8: ----5bee37ebfde51c72
00be: 
=> Send data, 342 bytes (0x156)
0000: --------------------------5bee37ebfde51c72

// The next line puts the broken entry into the cache (".." is actually a utf-8 char that curl doesn't display correctly)

002c: Content-Disposition: form-data; name="test"; filename=".."
0068: Content-Type: application/octet-stream
0090: 
0092: 
0094: --------------------------5bee37ebfde51c72

// This line is a prefix up to the broken character and would crash the parser

00c0: Content-Disposition: form-data; name="test"; filename=".."
00fc: Content-Type: application/octet-stream
0124: 
0126: 
0128: --------------------------5bee37ebfde51c72--
```

Thanks a lot again, @shkhln for providing a reproducer. I guess, it's a common enough case for multi file uploads of files with non-ascii characters, which are uncommon in English-speaking countries but less so any other countries.

(There's still related issue #1240 open. In theory, you shouldn't put non-ascii chars into the `filename` parameter but use `filename*` instead, but it seems support for that is something wild in reality).

/cc @sirthias this took us a few years to track down :)

**Comment by sirthias** [comment]
Ahh, damn.
I'm truly sorry about that!!
I've had a few of these "more bits than expected" issues myself recently and they are true beasts to find. Unfortunately even the `-Ywarn-numeric-widen` compiler settings (that I always have enabled) is no help here...

**Comment by sirthias** [comment]
One thought: Have you done a quick check of all `input(cursor)` and `byteAt(...)` call sites to look for possible bugs of the same kind that are unrelated to this issue?

**Comment by jrudolph** [comment]
> Ahh, damn.
> I'm truly sorry about that!!

No worries, tricky but fast code :)

> One thought: Have you done a quick check of all `input(cursor)` and `byteAt(...)` call sites to look for possible bugs of the same kind that are unrelated to this issue?

Yeah, I think I looked at more than the ones needed for this particular problem. At least in the HttpHeaderParser.

**Comment by jrudolph** [comment]
> Unfortunately even the `-Ywarn-numeric-widen` compiler settings (that I always have enabled) is no help here...

Yep, this one here is probably also about signed byte vs. unsigned char. So probably something like this happens:

```
scala> 0x82.toByte
res0: Byte = -126

scala> res0.toChar.toInt
res3: Int = 65410

scala> res0.toInt
res4: Int = -126

scala> (res0 & 0xff).toInt
res6: Int = 130

scala> (res0 & 0xff).toChar.toInt
res7: Int = 130
```

**Comment by sirthias** [comment]
Exactly.
It truly is a bummer that the JVM has no support for unsigned integer types.
It would make sooo many bugs simply disappear.

**Comment by YikSanChan** [comment]
@jrudolph Can you tag here when the fix is released?

**Comment by jrudolph** [comment]
> Can you tag here when the fix is released?

10.2.0-M1 already has the fix and we'll soon release 10.1.12 which will have the fix as well.

**Comment by raboof** [comment]
10.1.12 is now released

**Pull request merged**
