### PR TITLE
added Marshaller.oneOf(m1, m2) to JavaDSL (#1551)

### PR DESCRIPTION
**Pull request by n1ko-w1ll**
...to improve the Java DSL for two Marshallers (see #1551)

### CODE REVIEW

**Comment by jrudolph** [comment]
OK TO TEST

**Comment by jrudolph** [comment]
LGTM but PR validation failed because the code was not automatically formatted before being checked in. We enforce that all code has been auto-formatted so that running the build doesn't introduce spurious whitespace changes for the next person working on master.

Could you recompile so that the code is auto-formatted and commit the changes? Thanks.

**Comment by n1ko-w1ll** [comment]
Okay, I‘ll reformat the code and update the PR tomorrow 👍

**Comment by n1ko-w1ll** [comment]
I have different code style settings and IDE reformatted the copy & pasted javadoc. I've fixed the indentation.

**Comment by ktoso** [comment]
> I have different code style settings and IDE reformatted the copy & pasted javadoc. I've fixed the indentation.

If you compile using sbt it'll do the "right" formatting, independent of your IDE :)

**Pull request merged**
