### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by jlprat**
I directly copied the ones for Akka (thanks @raboof!) and removed the hint to other repos,
as we never get issues or feature requests for the wrong repo in Akka HTTP.

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by jlprat** [comment]
Well, at lest the queue seemed empty yes...

**Comment by ennru** [comment]
I think it would be good to help people to find the correct issue tracker for their thing.
Akka has this section in the templates
```
<!--
Please report issues regarding specific projects in their respective issue trackers, e.g.:
 - Akka HTTP: https://github.com/akka/akka-http/issues
 - Alpakka:   https://github.com/akka/alpakka/issues
 - Akka Persistence Cassandra Plugin: https://github.com/akka/akka-persistence-cassandra/issues
 - ...

Please explain your use case precisely, and if possible provide an example snippet.

Thanks, happy hakking!
-->
```

**Comment by jlprat** [comment]
Hi @ennru I can add those, sure! I didn't on purpose as it's not that common (never happen AFAIK) that somebody opened a ticket in Akka HTTP that was clearly an Alapakka or Akka one.

**Comment by ennru** [comment]
Ok, sounds good, if not needed here. I was in the midst to add some to Alpakka repositories and there we'll need it.

**Comment by jlprat** [comment]
We can add the other repos in here if you also want to add them to Alpakka. I'm all in for consistency

**Comment by ennru** [comment]
I guess you'll want a pointer to Akka main project there, instead of Akka Http.

**Comment by jlprat** [comment]
Cursed copy paste!!!

**Comment by raboof** [comment]
:smile: nice!

**Pull request merged**
