### PR TITLE
Prefer custom config values instead default ones #1492

### PR DESCRIPTION
**Pull request by apehovski**

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
Refs #1492

**Comment by jrudolph** [comment]
Hmm, I think we should consider a different solution. I guess we might want to remove the concrete values in the `akka.http.host-connection-pool` section of `reference.conf` so that in the default case the fallbacks are used.

**Comment by apehovski** [comment]
About fix - maybe it is not correct way to handle it, since I'm newcomer in architecture of akka-http :) 
But for checking possible issue I've made simple project:
https://github.com/apehovski/akka-http-client-sample

To check, run:
`python server.py`
(simple server to see incoming headers)
`sbt run`

Output of running python server for me:
```
User-Agent: akka-http/10.0.10
127.0.0.1 - - [24/Oct/2017 19:56:02] "GET / HTTP/1.1" 200 -
```

Not overridden header. But application.conf contains lines from akka-http docs.
Is it looks like issue or it's my misunderstanding? Thanks in advance for your time!

**Comment by jrudolph** [comment]
My suggestion was to remove everything under `akka.http.host-connection-pool.client` in the `reference.conf` and see if that would fix the issue as well. If yes, then that's the preferred resolution.

**Comment by jrudolph** [comment]
I'm closing this PR for now as there's a better solution as outlined in the comments here and in #1492.

**Pull request closed without merging**
