### PR TITLE
close websocket connection when idle configured timeout is reached 

### PR DESCRIPTION
**Pull request by kkonyshev**
References #2419

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Review by jrudolph — COMMENTED** [review]
Thanks, @kkonyshev.

I wonder if that fixes anything, have you tested it? We already have idle-timeouts in place, do you know of a reason why they wouldn't apply?

**Comment by kkonyshev** [comment]
No problem, @jrudolph.

Indeed, I tested it. 
The simplest way to verify the fix is to set 'periodic-keep-alive-max-idle' > 'connection-idle-timeout` (with enabled 'periodic-keep-alive-mode').

I didn't check why other idle-timeouts don't apply. Will have a look.

**Comment by kkonyshev** [comment]
@jrudolph , existing idle timeouts apply to http2 configuration only.

**Comment by kkonyshev** [comment]
@jrudolph , you are right, I will reuse the existing property and fix the PR. Thanks for the feedback.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one commit author (konstantin.konyshev@restore.energy, konstantin.konyshev@centrica.com) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one commit author (konyshev.konstantin@gmail.com) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Review by plzakj — APPROVED** [review]

**Comment by plzakj** [comment]
@jrudolph is it possible to proceed with this PR and also backport it to 10.1? We have verified that the changes also solve the issue #2419 on 10.1 in our case

**Comment by jrudolph** [comment]
Hi @kkonyshev, we might have misunderstood before. It's not clear to me why the expected functionality has not already been covered by the existing connection-level idle timeout. 

Is this fix for client or server side?

As I said before we might have been missing to apply the idle timeout for the `websocketClient` functionality but for the server side it should have worked before (and it seems this is also what the original reporter at #2419 mentioned?).

It would help if we could start with a test case that shows the unexpected behavior (e.g. in WebSocketIntegrationSpec) so we can verify that something is actually fixed.

**Comment by jrudolph** [comment]
Btw. 10.1.x is old by now and will only receive updates in rare cases.

**Comment by kkonyshev** [comment]
@jrudolph, I believe I got your point last time and made changes accordingly. The Server-side didn't implement timeout handling, hence, the existing connection-level idle timeout wasn't applied at all. I added missing BidiFlow foon the server-side (it will use the exiting connection-level server timeout settings).
I will check why tests have failed.

**Comment by plzakj** [comment]
@kkonyshev @jrudolph I was testing the changes on our side again and I was struggling a bit. I think I misunderstood as well. The changes from this PR apply bidirectionalIdleTimeout on the bidiflow stack which means that if there is e.g. ping being sent every 500ms and idle timeout set to 2s, then it will never timeout in the case pong responses are being lost.
Setting 'periodic-keep-alive-max-idle' > 'connection-idle-timeout` does not make sense to me.

In order to close the WS when pongs are being lost, I added a idleTimeout on the input flow (between masking.out and frameHandling.in). This causes timeout exception in the case there are no incoming frames during the timeout. Default is infinite. I'll run a separate pull request for this change.

@jrudolph I think the problem affects both server and client. When looking to HttpConnectionIdleTimeoutBidi - it applies bidirectionalIdleTimeout() which means that will not run into timeout as long as pings are being sent out?

**Comment by johanandren** [comment]
Closing this due to inactivity, please re-open if you still want to contribute a fix for https://github.com/akka/akka-http/issues/2419 (under the new license)

**Pull request closed without merging**
