### PR TITLE
Fix nightly build against Akka master

### PR DESCRIPTION
**Pull request by jlprat**
It failed because of the Actor for this example could not be compiled anymore. Now it is inlined again

### CODE REVIEW

**Comment by jlprat** [comment]
My bad, I removed the wrong file, I don't know how it happened. Fixing this

**Comment by jlprat** [comment]
I deleted the wrong file by mistake. Now should be good to go

**Comment by jrudolph** [comment]
Thanks @jlprat.

**Comment by jrudolph** [comment]
I reran nightlies manually and they are fixed again.

**Comment by jlprat** [comment]
I moved back to a file the Akka Actor example you inlined previously and that caused the nightlies fail :(

**Pull request merged**
