### PR TITLE
Fix message assertion in GracefulTerminsionSpec

### LINKED ISSUE #2309: Failed: GracefulTerminationSpec
https://jenkins.akka.io:8498/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.11.11/lastCompletedBuild/testReport/akka.http.scaladsl/GracefulTerminationSpec/Graceful_termination_should_stop_accepting_new_connections/

Akka has changed the message of a TCP connection refused that this relied on

### PR DESCRIPTION
**Pull request by chbatey**
* To work with different versions of Akka that have a slightly different
error message

Fixes #2309

### CODE REVIEW

**Comment by raboof** [comment]
hmm

**Comment by chbatey** [comment]
It wasn't me!

**Comment by raboof** [comment]
Added #2349

**Comment by raboof** [comment]
This issue was also independently fixed via #2312

**Pull request closed without merging**
