### PR TITLE
Preserve original response headers during server termination #3818

### PR DESCRIPTION
**Pull request by kstokoz**
References #3818

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by raboof** [comment]
OK TO TEST

**Review by raboof — APPROVED** [review]
thanks!

**Review by jrudolph — APPROVED** [review]
LGTM, thanks good catch.

**Pull request merged**
