### PR TITLE
Avoid using Future in a string concatenation

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
I whitelisted you for jenkins to trigger automatically btw

**Comment by kubukoz** [comment]
Thank you :)

**Comment by kubukoz** [comment]
I'm loving how no build is ran when only docs are changed in a PR, too

**Comment by kubukoz** [comment]
```
Passed: Total 1108, Failed 0, Errors 0, Passed 1108, Pending 38
[error] (akka-http-core/test:test) sbt.TestsFailedException: Tests unsuccessful
```

I'm lost :P

**Comment by ktoso** [comment]
Click the "show all logs".

```
[info] - should properly bind and handle a server with a flow (with four parameters) *** FAILED ***
[info]   java.util.concurrent.TimeoutException:
[info]   at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1763)
[info]   at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1907)
[info]   at scala.concurrent.java8.FuturesConvertersImpl$CF.scala$concurrent$java8$FuturesConvertersImpl$CF$$super$get(FutureConvertersImpl.scala:84)
[info]
```

Unrelated.

**Comment by kubukoz** [comment]
Oh, I see, thanks. Also, TIL pending tests :D

**Comment by kubukoz** [comment]
Fixed, squashed

**Comment by ktoso** [comment]
Thanks!

**Comment by ktoso** [comment]
Resolves https://github.com/akka/akka-http/issues/349

**Comment by ktoso** [comment]
Please link back to issues a PR resolves :)

**Comment by kubukoz** [comment]
I did, in the commit :P

**Comment by ktoso** [comment]
In comments. In commit does not link issues.
Thanks in advance.

**Comment by kubukoz** [comment]
Sure, I'll try to remember next time ;)

**Pull request merged**
