### PR TITLE
=pro Update to sbt 1.1.0

### PR DESCRIPTION
**Pull request by jlprat**
I just realized we had RC4 in `project/build.properties`

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM thanks

**Comment by jlprat** [comment]
I see you created the same PR just after me!

**Comment by ktoso** [comment]
Yeah sorry I missed it at first ;)

**Comment by jlprat** [comment]
Oh, no worries, first I thought I was the one who missed an existing PR!

**Pull request merged**
