### PR TITLE
Add `endsWith` predicate to `Uri.Path`

### PR DESCRIPTION
**Pull request by sirthias**
Adds a small helper function that I would have liked to use myself.

This time I was looking for a Java API equivalent but I believe there is none for this part of the model, is there?

### CODE REVIEW

**Comment by jrudolph** [comment]
Thanks, @sirthias, and sorry for keeping it around for so long.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by sirthias** [comment]
Thank you, @jrudolph, and sorry, @raboof, for not reacting earlier.
I somehow missed your comment re the merge conflict.
I'll push a fix later today..

**Comment by jrudolph** [comment]
Already merged it ;)

**Comment by sirthias** [comment]
@jrudolph, ah right. Even better! :)

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Pull request merged**
