### PR TITLE
Allow Content-Range to be used as a request header #932

### PR DESCRIPTION
**Pull request by desmondyeung**
Changes the type of `Content-Range` from `ResponseHeader` to `RequestResponseHeader`

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @desmondyeung,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jlprat** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Please ref the issue and close it as well when merging :)

**Comment by ktoso** [comment]
Refs #932

**Pull request merged**
