### PR TITLE
Avoid adaptation in RequestContext 'complete' as well

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by raboof** [comment]
> This is basically low-level API, so a bit of inconvenience should be fine. WDYT?

Yeah, I'm also fine with keeping it as-is.

> Did it turn up somewhere?

Only a couple internally, #3337

**Comment by ennru** [comment]
I found a legit one in a docs spec in #3345.

**Comment by jrudolph** [comment]
> I found a legit one in a docs spec in #3345.

This usage can be replaced by a regular `complete` as well, see #3354

**Comment by jrudolph** [comment]
I'm closing this one for now.

**Pull request closed without merging**
