### PR TITLE
docs: add example for Get request with query parameters

### PR DESCRIPTION
**Pull request by nikhilpatil**
This is quite a common requirement and nowhere mentioned in the docs explicitely. A question on stackoverflow (with 11k views) has an [answer](https://stackoverflow.com/a/31939776/154325) to this. But I believe inclusion of a simple example in official documentation will help developers a great deal.

References #xxxx

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @nikhilpatil,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Review by raboof — APPROVED** [review]
I like having more 'simple' examples early on.

This is already an improvement, so LGTM'ing. I think we could go a few steps further, though: perhaps here `Uri("https://akka.io?foo=bar")` would be nicer as a first step, and then linking to https://doc.akka.io/docs/akka-http/current/common/uri-model.html#query-string-in-uri and having this example over there?

Also it would be great to also have a Java version of this example

**Comment by nikhilpatil** [comment]
> I like having more 'simple' examples early on.
> 
> This is already an improvement, so LGTM'ing. I think we could go a few steps further, though: perhaps here `Uri("https://akka.io?foo=bar")` would be nicer as a first step, and then linking to https://doc.akka.io/docs/akka-http/current/common/uri-model.html#query-string-in-uri and having this example over there?
> 
> Also it would be great to also have a Java version of this example

That makes sense. First part is straight forward. I will need help - especially with wording - for adding example to the query-string-in-uri section. I'll give it a shot though and will await comments on it 👍

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by nikhilpatil** [comment]
@raboof have tried to distribute examples over two pages as suggested. I couldn't put the original example (from the first commit) at https://doc.akka.io/docs/akka-http/current/common/uri-model.html#query-string-in-uri because that didn't seem like the right place to talk about `HttpRequest` (or `Get`). So just put a relevant example there, but If the reader starts from HttpRequest's page, I hope with the link in the "Note", they will get a clear picture about how to use the Uri and Query API with HttpRequest! 
Awaiting review comments, if any :)

**Review by raboof — APPROVED** [review]
Thanks, nice improvement!

**Review by jrudolph — APPROVED** [review]
LGTM

**Pull request merged**
