### PR TITLE
Fix scenario where buffered element is lost

### PR DESCRIPTION
**Pull request by raboof**
Feels like this is more complicated (and harder to test) than it
should be, but I don't see an obvious way to simplify.

### CODE REVIEW

**Comment by jrudolph** [comment]
Can you explain how the scenario could be observed?

**Comment by raboof** [comment]
> Can you explain how the scenario could be observed?

I saw it when I sent a request and then immediately completed the source.

I guess in 'real life' that might be triggered by half-closed TCP connections, though it is unclear how a HTTP/2 server should handle half-closed TCP connections (everything I can find is about HTTP/1 and it seems there's no consensus there either...).

The spec says https://tools.ietf.org/html/rfc7540#section-5.4.3 about automatically retrying failed requests from half-closed connections, but nothing about whether requests may be actively aborted in that case.

**Comment by jrudolph** [comment]
HTTP/2 has an indication of which requests have been processed in the GOAWAY frame.

**Comment by jrudolph** [comment]
> I saw it when I sent a request and then immediately completed the source.

Which source was that? For the HTTP/2 client or server? I guess for the client a nice behavior would be that we don't close the TCP connection for a time when there's still a response outstanding.

**Comment by raboof** [comment]
> Which source was that?

(this was the 'test source' exercising the server stack in #3369)

**Pull request closed without merging**
