### PR TITLE
More logging for #1667

### PR DESCRIPTION
**Pull request by raboof**
Refs #1667

### CODE REVIEW

**Comment by jrudolph** [comment]
Yeah debug level OFF rarely makes sense.

**Comment by raboof** [comment]
Jup let's set it back to `ERROR` or `WARNING` eventually, but for now DEBUG would be interesting because I'm curious whether we'll see the expected "Request has {} retries left, retrying..." logging.

**Comment by jrudolph** [comment]
I yesterday fixed things that might have been related. Hard to say.

**Comment by raboof** [comment]
it seems to have failed in 591d195853d9f857655aaf0756e1af34339aceca (https://jenkins.akka.io:8498/job/pr-validator-akka-http/2065/) but there the loglevel was still on ERROR :/

**Comment by raboof** [comment]
But running just the failing test on repeat seems stable (https://jenkins.akka.io:8498/job/akka-http-repeat/) :/

**Pull request merged**
