### PR TITLE
Add step to update the Akka Http version on akka.io/docs

### PR DESCRIPTION
**Pull request by mikela**
Hi, I believe the step to update the Akka Http version on https://akka.io/docs/ is missing so I just added it.

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
Actually it seems to be already there on line 33, but indeed for 10.1.8 I missed it - maybe make that its own bullet?

**Comment by mikela** [comment]
You are absolutely right! Sounds good :+1:

**Comment by mikela** [comment]
Feel free to edit all you deem necessary of course! I just "denormalized" the bullet point :laughing:

**Pull request merged**
