### PR TITLE
Add reference to SBT/Gradle/Maven artifact inclusion details

### PR DESCRIPTION
**Pull request by retrospectacus**

### CODE REVIEW

**Comment by ktoso** [comment]
Good idea to link back I think. Not sure if this is the best place hmm...

cc @akka/akka-http-team

**Comment by jlprat** [comment]
What about under `docs/src/main/paradox/scala/http/introduction.md` (and the Java one as well) just below the explanation of the different modules?

**Comment by jrudolph** [comment]
OK TO TEST

**Comment by jrudolph** [comment]
Hmm, yes, I agree with @jlprat that this rather belongs on the introduction page..

**Comment by jrudolph** [comment]
Amended the commit to move the line around to the introductory page below the sbt config line.

**Comment by jrudolph** [comment]
Thanks, @retrospectacus.

**Pull request merged**
