### PR TITLE
Fixing some typos and grammatical issues.

### PR DESCRIPTION
**Pull request by SeerUK**
Just found a couple of issues in the Custom Directives docs, thought I'd quickly submit a patch.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @SeerUK,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jrudolph** [comment]
OK TO TEST

**Comment by SeerUK** [comment]
Signed! :)

**Comment by jrudolph** [comment]
Thanks :)

**Pull request merged**
