### PR TITLE
Add HTTP status code 421

### PR DESCRIPTION
**Pull request by aarongut**
Status code document at https://tools.ietf.org/html/rfc7540#section-9.1.2

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @aarongut,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by aarongut** [comment]
CLA signed

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Hmm, sounds good; I think I'd want to link to the RFC from the code since it's not as widely known I think?

**Comment by aarongut** [comment]
Would that be consistent with the other codes? It is listed in the wikipedia page, and the only code with a comment is 420, which is Twitter specific.

**Comment by ktoso** [comment]
Clarity is more important here than being consistent with not documenting a status code ;) I mean, it seems this one was defined only recently in the HTTP/2 RFC? On my phone and could not look very deep into it but adding s comment should not hurt I think :)

**Comment by jrudolph** [comment]
Thanks, @aarongut.

**Pull request merged**
