### PR TITLE
Update for Migration guide with Route type

### PR DESCRIPTION
**Pull request by sidfeiner**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @sidfeiner,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jrudolph** [comment]
OK TO TEST

**Comment by typesafehub-validator** [comment]
Hi @sidfeiner,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
Great, thanks! That helps a lot :)
Last thing to be done here is signing the CLA (via github, pretty simple http://www.lightbend.com/contribute/cla/verify ), which basically confirms that you hand over your contribution under our license (Apache 2 etc).

**Comment by sidfeiner** [comment]
I've signed the CLA

**Comment by ktoso** [comment]
Great, thanks - confirmed the signature :)
Test failure was unrelated, this is just docs changes.

**Comment by sidfeiner** [comment]
Haha yeah, I guessed :) And with pleasure!

**Pull request merged**
