### PR TITLE
Update year in Contributing

### PR DESCRIPTION
**Pull request by jlprat**
Update year in Contributing

### CODE REVIEW

**Comment by ktoso** [comment]
LGTM, thanks :)

**Comment by ktoso** [comment]
Someone else seems to be working on updating all files already :)

**Comment by jlprat** [comment]
I saw a PR for akka/akka and I decided to update only the text files

**Comment by ktoso** [comment]
Hm right it was on akka/akka it seems. We should do this on all projects actually I guess.

**Comment by jlprat** [comment]
I could do a search and replace on akka-http. These changes were made on mobile :smile:

**Comment by ktoso** [comment]
I'll check with the team tomorrow if we need to do those mass renumberings actually, and will let you know.

**Pull request merged**
