### PR TITLE
Add realm to provided credentials

### PR DESCRIPTION
**Pull request by odd**
This enables authenticators to access both the realm and 
identifier used for authentication.

For extracting only the identifier like before this change, 
an extractor is provided using the previous name (`Provided`).

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by johanandren** [comment]
Unrelated failure (#2108)

**Comment by johanandren** [comment]
PLS BUILD

**Comment by johanandren** [comment]
There is also a MiMa failure though. Skimmed quickly but couldn't determine if it's an ok change with regards binary compatibility or not.

**Comment by johanandren** [comment]
PLS BUILD

**Comment by johanandren** [comment]
I think we need you to do a rebase on current master and push that.

**Comment by raboof** [comment]
Closing since there hasn't been activity on this PR for a while, though this does seem like a useful feature - feel free to reopen, then the next step is to look at the binary compatibility challenge!

**Pull request closed without merging**
