### PR TITLE
Add Java DSL optionMarshaller #1247

### LINKED ISSUE #1247: Reusing the ToResponseMarshaller
I have a typical use case where I have an arbitrary resource, `T` and a corresponding endpoint `GET /T`. This maps to a method which returns a `CompletionStage<Optional<T>>` now I wasn't able to find any predefined routing directive that would let me return `200 OK` if the optional contains the resource and `404 Not found` if the resource was not found.

I am thinking I might have to use the `completeWithFuture` that accepts a `CompletionStage<HttpResponse>` and that's fine except I also need to serialise the POJO into a JSON response and I wasn't able to find something akin to  the `completeOK` overload which accepts a value `T` and a `Marshaller<T, ResponseEntity>`. Ideally if I could find a function accepting `T` and `Marshaller<T, ResponseEntity>` and returning a `HttpResponse`.

### PR DESCRIPTION
**Pull request by Gabology**
Fixes #1247 by adding a `Marshaller<Optional<A>, RequestEntity>` that is usable from Java.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Gabology,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by lightbend-cla-validator** [comment]
Hi @Gabology,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by Gabology** [comment]
I have signed the CLA.

**Comment by ktoso** [comment]
OK TO TEST

**Pull request merged**
