### PR TITLE
tests: widen EntityStreamingSpec patience

### LINKED ISSUE #3495: Failed: EntityStreamingSpec.client-consume-streaming-json
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.1/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.12.10,jdk=AdoptOpenJDK%208/1035/testReport/junit/akka.http.scaladsl.server/EntityStreamingSpec/client_consume_streaming_json/

```
 A timeout occurred waiting for a future to complete. Queried 2 times, sleeping 15 milliseconds between each query.
	at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:538)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
	at akka.http.scaladsl.server.EntityStreamingSpec.$anonfun$new$11(EntityStreamingSpec.scala:123)
```

### PR DESCRIPTION
**Pull request by raboof**
Seen in #3495

### CODE REVIEW

**Comment by jrudolph** [comment]
It failed on release-10.1, should we only do it there? Or backport?

**Comment by raboof** [comment]
I think it makes sense in general, as the default patience could fairly plausibly be exceeded by a long GC. So I'd prefer to have it both on master and backported.

**Review by jrudolph — APPROVED** [review]
LGTM

**Comment by jrudolph** [comment]
> I think it makes sense in general, as the default patience could fairly plausibly be exceeded by a long GC. So I'd prefer to have it both on master and backported.

:+1:, can you do the backport?

**Pull request merged**
