### PR TITLE
+htp #1025 Implement client pool monitoring

### LINKED ISSUE #1025: Add some kind of client pool monitoring
We have several tickets of hung pools and it's always hard to find out what's going on. It would be nice if there would be some (internal / unstable?) API to allow users to check what the pool is doing right now (and why). Using the flight recorder would be nice to allow recording of recent events to understand how the pool ended up in the current state.

### PR DESCRIPTION
**Pull request by jypma**
This commit introduces a first attempt at a generic statistics and
metrics mechanism to akka-http, so we can allow users to use their
monitoring implementation of choice.

Metrics are sent to the system event bus through HttpMeasurements
messages, which wrap a sealed trait (right now limited to Gauge only).

This commit adds client pool monitoring only, but for both pool implementations.
We can later add request monitoring (times, status codes), and server monitoring.

Fixes #1025 .

### CODE REVIEW

**Comment by jypma** [comment]
This may also make issues like https://github.com/akka/akka-http/issues/843 and https://github.com/akka/akka-http/issues/1186 easier to debug, by showing how much is connected / queued up at any point in time.

**Comment by jypma** [comment]
@akka/akka-http-team tests green, ready for review.

**Comment by jrudolph** [comment]
Thanks a lot, @jypma. Just wanted to say, that I didn't get to reviewing your PRs in detail due to holidays and other duties. Will hopefully get to it soon!

**Comment by ANorwell** [comment]
This looks neat, any updates?

**Comment by gosubpl** [comment]
@ANorwell there is new Pool implementation under way: https://github.com/akka/akka-http/pull/1533

**Comment by jypma** [comment]
@akka/akka-http-team Tests green. Anyone willing to take a look?

**Comment by zackangelo** [comment]
Did this ever go anywhere? Happy to jump in and help push this forward if it's needed.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Pull request closed without merging**
