### PR TITLE
update akka version to 2.5.11 and fix docs #1892

### PR DESCRIPTION
**Pull request by shkoder**
ref #1892

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by raboof** [comment]
Note that master was already updated to 2.5.10 in #1890 - some of the doc changes might not make sense (anymore)?

**Comment by shkoder** [comment]
thanks @raboof
the problem is #1890 did not update `akka.AkkaDependency#defaultAkkaVersion` - it is `2.5.9` on master at the moment, which fails `sbt docs/paradoxMarkdownToHtml` (checked in scope of `validatePullRequest`.
This PR fixes docs on top of what has been already done in #1890

**Comment by raboof** [comment]
Aah you're right, good one! `@javadoc[@unidoc[...]]` might not be needed, just `@javadoc[...]` should probably be sufficient?

**Comment by shkoder** [comment]
good point, fixed

**Comment by jrudolph** [comment]
Thanks a lot, @shkoder!

**Pull request merged**
