### PR TITLE
updated outdated SecurityDirectives documentation

### PR DESCRIPTION
**Pull request by Prithvirajbilla**
Fixes akka/akka-http#1715

### CODE REVIEW

**Comment by jlprat** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks for researching the changes

**Comment by ktoso** [comment]
Merge once updated branch passes

**Comment by Prithvirajbilla** [comment]
Thank you. :) 

The tests are passed with updated branch.  I don't see any merge button to merge this change.

**Comment by ktoso** [comment]
> I don't see any merge button to merge this change.

@jlprat does as do other members of the akka-http team though ;-)
Thanks for the contrib

**Comment by jlprat** [comment]
Sorry, I wasn't able to come back to this issue before you merged, next time 🙂

**Comment by ktoso** [comment]
Sorry, my bad! Should have let it there. Will train my zen about this :)

**Comment by jlprat** [comment]
No worries! It's good to merge quickly first time contributors!
BTW thanks and welcome @Prithvirajbilla

**Pull request merged**
