### PR TITLE
Update to sbt 1.0.4

### PR DESCRIPTION
**Pull request by ktoso**

### CODE REVIEW

**Comment by raboof** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
I disabled a0 for building akka-http, it seems to be too slow, failing most PR runs.

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
Failure was #1560

**Comment by raboof** [comment]
PLS BUILD

**Comment by ktoso** [comment]
Why do you hate us jenkins ;-)

**Comment by raboof** [comment]
Hm #1560 again

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
I can actually reproduce that... looking into it.

**Comment by jrudolph** [comment]
PLS BUILD

**Pull request merged**
