### PR TITLE
Add minConnections modifier to ConnectionPoolSettings #1525

### PR DESCRIPTION
**Pull request by RustedBones**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Refs #1525

**Comment by ktoso** [comment]
LGTM, may need a MiMa fix... though maybe that class is already filtered.

**Comment by jrudolph** [comment]
PLS REBUILD

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
Thanks, @RustedBones.

**Pull request merged**
