### PR TITLE
[wip - do not merge] h2spec compliance - size check added to PingFrame (#245)

### PR DESCRIPTION
**Pull request by gosubpl**
Size checks added to:
* PingFrame

StreamId checks added to:
* PingFrame

### CODE REVIEW

**Comment by gosubpl** [comment]
Refs #245

**Comment by ktoso** [comment]
Which one should pass now?

**Comment by gosubpl** [comment]
https://jenkins.akka.io:8498/job/pr-validator-akka-http/564/testReport/h2spec-6/7%20PING/h2spec_Sends_a_PING_frame_with_a_length_field_value_other_than_8/
and it says `Fixed` now
And PRIORITY_FRAME size should fail, but didn't: https://jenkins.akka.io:8498/job/pr-validator-akka-http/564/testReport/h2spec-6/3%20PRIORITY/

**Comment by gosubpl** [comment]
OK, now I have added `streamId` check to `PING_FRAME` - this test was `Skipped` should be something else now: https://jenkins.akka.io:8498/job/pr-validator-akka-http/564/testReport/h2spec-6/7%20PING/h2spec_Sends_a_PING_frame_with_the_stream_identifier_that_is_not_0x0/

**Comment by gosubpl** [comment]
OK, now all `PING_FRAME` tests have status `Passed` - https://jenkins.akka.io:8498/job/pr-validator-akka-http/566/testReport/h2spec-6/7%20PING/

And I think the `PRIORITY_FRAME` mystery is solved - the `h2spec` doesn't send `PRIORITY_FRAME`, it sends `HEADERS_FRAME` with priority settings set - https://github.com/summerwind/h2spec/blob/v1.5.0/6_3.go
Will continue with this PR adding other simple validations.

**Comment by gosubpl** [comment]
@ktoso @jrudolph @schmitch will be adding to this PR additional simple validations to make `h2spec` happy

**Comment by ktoso** [comment]
You'll sadly have to rebase. Sorry about that

**Comment by gosubpl** [comment]
@ktoso no problem, will probably reopen from scratch anyway.

**Comment by gosubpl** [comment]
Closing. Reopened in https://github.com/akka/akka-http/pull/740

**Pull request closed without merging**
