### PR TITLE
=htp #930 replace IteratorInterpreter usage by asynchronous folding

### PR DESCRIPTION
**Pull request by jrudolph**
Refs #930.

### CODE REVIEW

**Comment by viktorklang** [comment]
@jrudolph Cool. Do we have any results for the performance impact of the change? :)

**Comment by ktoso** [comment]
@viktorklang this is to unlock using akka-http with the new materializer, perofrmance impact we'll consider separately. This week we need it to work on the new one and look at performance then.

I'd vote to merge to unlock progress

**Comment by viktorklang** [comment]
Absolutely

-- 
Cheers,
√

**Comment by jrudolph** [comment]
Let's not merge this before getting at least some rough numbers about how much slower it will be. I didn't know before that `IteratorInterpreter` would be easy enough to maintain so maybe we can keep it.

**Comment by johanandren** [comment]
We should make it public api if we keep it though, depending on internals is not nice.

**Comment by jrudolph** [comment]
This has been included in #958.

**Pull request closed without merging**
