### PR TITLE
Typo in docs

### PR DESCRIPTION
**Pull request by lrimkus**
Typo in docs

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @lrimkus,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jlprat** [comment]
OK TO TEST

**Comment by lrimkus** [comment]
Signed the CLA

**Comment by jlprat** [comment]
As it is a non controversial change and the typo was a clear one, I'll merge this one.

**Pull request merged**
