### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by golem131**
- akka 2.5.6 -> 2.5.7
- akka 2.4.19 -> 2.4.20
- cross Scala 2.12.3 -> 2.12.4

### CODE REVIEW

**Comment by jonas** [comment]
OK TO TEST

**Comment by raboof** [comment]
`genjavadoc-plugin_2.11.12;0.10: not found` - [looks like](https://travis-ci.org/lightbend/genjavadoc) indeed that isn't built for 2.11.12 yet

**Comment by Philippus** [comment]
should `akkaVersion` go to 2.4.20 ?

**Comment by raboof** [comment]
Hmm, `Error: Unable to access jarfile /usr/share/sbt/bin/sbt-launch.jar` on `johannes`?

**Comment by raboof** [comment]
PLS BUILD

**Comment by golem131** [comment]
@Philippus 
Not found
com.typesafe.genjavadoc#genjavadoc-plugin_2.11.12;0.10 

So we cannot update to Scala 2.11.11 to 2.11.12 now.

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
@golem131 if you remove the h2spec changes we could at least merge the other version updates.

**Comment by jrudolph** [comment]
Thanks a lot @golem131. I guess it would be interesting to also try the h2spec update but we can do that in another PR.

**Comment by golem131** [comment]
@jrudolph u welcome. yes, i would try update h2spec later, you can assign ticket on me

**Comment by jrudolph** [comment]
Thanks, @golem131. I created https://github.com/akka/akka-http/issues/1578 to track this. I couldn't assign you, though.

**Pull request merged**
