### PR TITLE
build: replace jabba by proper debian installation

### PR DESCRIPTION
**Pull request by jrudolph**

### CODE REVIEW

**Review by raboof — APPROVED** [review]
IIRC we moved to jabba because they make it easier to switch to specific other versions, but I agree it seems to be causing more trouble than it solves now.

**Comment by ignasi35** [comment]
> IIRC we moved to jabba because they make it easier to switch to specific other versions, but I agree it seems to be causing more trouble than it solves now.

How about converging to `sdkman`? Either by copy-pasting the YAML from https://github.com/scala/scala-dev/blob/scala-dev/travis/default.yml or using it as a parent (related to https://github.com/akka/akka-meta/issues/141)

**Comment by ignasi35** [comment]
> IIRC we moved to jabba because they make it easier to switch to specific other versions, but I agree it seems to be causing more trouble than it solves now.

Some of the issues in jabba come from caching the JDKs. TIL TravisCI [recommends _not_ caching JDKs](https://docs.travis-ci.com/user/caching/#things-not-to-cache). If I'm reading this PR correctly, the suggested change would not cache the JDK either, right?

Maybe an intermediate solution is to remain in jabba without caching JDKs?

**Comment by jrudolph** [comment]
What's the precedence for using sdkman as an official way of installing packages? I'd vote for using an official repository instead of introducing unnecessary third-parties. I'd rather go back to manual downloading of an JDK instead of using another tool.

**Comment by ignasi35** [comment]
> What's the precedence for using sdkman as ...

Mostly consistence with other projects in the org.

**Comment by jrudolph** [comment]
Let's try to merge this and see if it works.

**Pull request merged**
