### PR TITLE
Fix broken snip link in source streaming support #797

### PR DESCRIPTION
**Pull request by jlprat**
Issue: #797 
Snippet of code for source streaming support is broken

### CODE REVIEW

**Comment by ktoso** [comment]
Please keep this open for a bit so it serves as a reminder to fix pr validation, hope to do it tomorrow

**Comment by jlprat** [comment]
Changed the title to make it more explicit

**Comment by jonas** [comment]
Took the liberty to merge this given we fixed PR validation.

**Comment by ktoso** [comment]
Yup awesome :) thanks

**Pull request merged**
