### PR TITLE
Improve http client documentation

### PR DESCRIPTION
**Pull request by jtwarren**
Improves the examples by removing imports from the top of the file and explicitly importing inline within examples.

I'm happy to go through other parts of the documentation, just want to make sure I'm on the right track first!

cc @ktoso, per https://github.com/akka/akka-http/pull/487#issuecomment-258929762.

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Thanks a lot for the PR :-) 
Changes like this are very useful, thanks!
If you have the time going through other examples like this would be great - newcomers get lost if we don't have the imports so it's really good to have them properly inside the example snippets.

**Comment by jtwarren** [comment]
@ktoso the test failure looks unrelated to my change, but let me know if I'm wrong:
```
HttpServerBluePrint.ControllerStage: requirement failed: Cannot pull closed port (requestParsingIn), inside HttpRequest(HttpMethod(POST),http://example.com/,List(Host: example.com, Expect: 100-continue, Timeout-Access: <function1>),HttpEntity.Chunked(application/octet-stream),HttpProtocol(HTTP/1.1))
```

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by ktoso** [comment]
Thanks a lot :)

**Pull request merged**
