### PR TITLE
Update docs to reference new jetty-alpn version

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by jrudolph** [comment]
Can we automate with paradox variables?

**Comment by raboof** [comment]
Hmm, we could remove the duplication (the same version being mentioned twice), but not really beyond that I think?

**Comment by ktoso** [comment]
> Can we automate with paradox variables?

Doing the same as we have with the akka version should be doable right; would be an improvement I guess just in the way of remembering we have that version in there somewhere even ;)

**Comment by jrudolph** [comment]
> Hmm, we could remove the duplication (the same version being mentioned twice), but not really beyond that I think?

I meant feeding the version from our build file where we mention the version number for running the HTTP/2 tests. Wouldn't that be possible?

**Comment by raboof** [comment]
Ah I didn't realize we use it in tests - I'll give it a shot!

**Pull request merged**
