### PR TITLE
=pro replace bintray-sbt by plain maven publish solution

### PR DESCRIPTION
**Pull request by jrudolph**
/cc @2m

### CODE REVIEW

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by 2m** [comment]
I think this is great if we can publish straight to maven repository. Have you checked if a new version is created in the bintray web ui when published like this?

**Comment by ktoso** [comment]
Works for me, though this means we must update the: https://github.com/akka/akka-http/blob/master/RELEASING.md with the actual steps to be performed for a release now.

**Comment by ktoso** [comment]
Resolved conflicts again, yay or nay? I don't care too much ;)

**Comment by jonas** [comment]
I can rebase it you'd like

**Comment by ktoso** [comment]
Ping, yay or nay?

**Comment by jrudolph** [comment]
Let's stash and close for now. Not using sbt-bintray would be nice but maybe currently not worth the extra effort required.

**Comment by ktoso** [comment]
+1, I agree. We can come back to this in case of some more free time ;)

**Pull request closed without merging**
