### PR TITLE
Fix directive cross references

### PR DESCRIPTION
**Pull request by jonas**
With incidental fixes of some recently added snippet links which suggests that we should start building the docs for every PR to avoid such errors in the future.

### CODE REVIEW

**Comment by jonas** [comment]
Weird that additional commits has been added to the PR. Did somebody push anything?

**Comment by ktoso** [comment]
We had to do bad things to master, can you rebase this one?

**Comment by jonas** [comment]
Done.

PLS BUILD ALL

**Comment by ktoso** [comment]
LGTM, thanks 👍

**Pull request merged**
