### PR TITLE
=htc Relocate HttpResponseParser.stage to tests

### PR DESCRIPTION
**Pull request by leachbj**
This stage is no longer required since 9dc474a1 converted HttpResponseParser
to a GraphStage.

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TES

**Comment by ktoso** [comment]
OK TO TEST

**Comment by jrudolph** [comment]
Thanks, @leachbj. LGTM

**Comment by ktoso** [comment]
LGTM

**Comment by ktoso** [comment]
Thanks!

**Pull request merged**
