### PR TITLE
The scaladsl route seal example was leaking an actor system

### PR DESCRIPTION
**Pull request by johanandren**
Which in turn would hang the entire test suite

### CODE REVIEW

**Comment by johanandren** [comment]
Not sure, I didn't investigate further than looking at the other `compileOnly` style tests and saw they were different.

**Comment by ktoso** [comment]
Yep, that's the thing then - very weird but I remember that used to be the thing (and why we invented the compile only thing)

**Comment by ktoso** [comment]
PLS BUILD

**Comment by ktoso** [comment]
Previous failure is known and unrelated https://github.com/akka/akka-http/issues/1063

**Comment by ktoso** [comment]
Merging as it was causing trouble to people and this certainly is what it was supposed to be to begin with 👍

**Comment by jrudolph** [comment]
Do we understand why it was leaking and hanging the test suite only now? Thanks anyway for fixing it quickly. :+1:

**Comment by johanandren** [comment]
I'd expect `compileOnlySpec` to not trigger creation of the actor system even if called from the constructor like that, but I didn't dig deeper.

**Comment by jrudolph** [comment]
Maybe it was that a file without any tests still runs the constructor (which creates the ActorSystem) but doesn't run the `afterAll`?

**Comment by ktoso** [comment]
> Maybe it was that a file without any tests still runs the constructor (which creates the ActorSystem) but doesn't run the afterAll?

AFAIR that's exactly the case - it would not run beforeAll / afterAll hooks when no tests are detected. But we create the system not in a hook, thus the leak. 

I think we had this some time in the past somewhere else too

**Pull request merged**
