### PR TITLE
Remove custom akka api mapping

### PR DESCRIPTION
**Pull request by jonas**
No needed after upgrading to 2.4.12

### CODE REVIEW

**Comment by jonas** [comment]
Looks like another case of the proxy error
```
[error] Server access Error: Connection refused url=https://proxy-ch.typesafe.com:8082/artifactory/repo/net.virtual-void/sbt-dependency-graph/scala_2.10/sbt_0.13/0.8.0/ivys/ivy.xml
[error] Server access Error: Connection refused url=https://proxy-ch.typesafe.com:8082/artifactory/repo/net/virtual-void/sbt-dependency-graph_2.10_0.13/0.8.0/sbt-dependency-graph-0.8.0.pom
```

**Comment by ktoso** [comment]
I reconfigured the servers, should work now.

**Comment by ktoso** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
LGTM, let's wait for another PR build.

**Comment by jrudolph** [comment]
Great, thanks @jonas. I checked that the mapping works manually.

**Pull request merged**
