### PR TITLE
Add extend documentation for headerValue with an example how the use …

### LINKED ISSUE #639: Extract a header value or return default
I some situation it would be handy to for the headerValue* directives to allow to specify a default value that is used if the header is not present.

for headerValueByName this could look like this:

`def headerValueByName(headerName: String, default: String): Directive1[String] =
    headerValue(optionalValue(headerName.toLowerCase)) | provide(default)`

### PR DESCRIPTION
**Pull request by zettelmj**
…headerValue and provide to get a header value if present or return a default

This should fix #639.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @jzettelmeyer,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by zettelmj** [comment]
Just signed the CLA

**Comment by ktoso** [comment]
LGTM, thanks a lot! :-)

**Comment by ktoso** [comment]
OK TO TEST

**Comment by typesafehub-validator** [comment]
Hi @jzettelmeyer,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
Why closing?

**Comment by zettelmj** [comment]
@ktoso i messed up my git identity. I mixed two identities. I opened #666 that has the right identity and corresponding ssh key.

**Comment by ktoso** [comment]
Oh, okey. Thanks, closing this one then.
And you even got a nice number for that PR 😉

**Pull request closed without merging**
