### PR TITLE
[WIP] fail ws flow on idle timeout

### PR DESCRIPTION
**Pull request by johanandren**
Refs #1026

This is the first version I got to work, not sure about the consequences, needs both the custom idle stage that fails upstream rather than downstream _and_ the delay as close to the user flow as possible, not 100% sure but think that is because failing the upstream also leads to the connection failing and that in turn starts to cancel stages up the stream.

### CODE REVIEW

**Comment by johanandren** [comment]
Crap. Forgot that we made the blueprint reusable.

**Comment by johanandren** [comment]
Grün, grün, grün sind alle meine Kleider! (actually they are all black, but the Jenkins build is green, woho!)

**Comment by jrudolph** [comment]
That would also mean that the special IdleTimeout stage cannot help in all cases, because emitting a failure is enough to retrigger the behavior on a higher stage.

Another thing that needs to be tested is the behavior of still running message input and output streams.

**Comment by ktoso** [comment]
Hmm yeah very tempting to take a big step back as we discussed on chat and here https://github.com/akka/akka/issues/17997 and think about bidirectional stages and cancellation in general before attacking this one hm

**Comment by johanandren** [comment]
Should I close this PR then, given the "take a step back" and the fix just being duct-tape?

**Comment by ktoso** [comment]
Hmm, this would relate to the ping/pong stuff as well actually. Do you want to revive this Johan or we close it for now?

**Comment by johanandren** [comment]
Yeah I guess we can close it for now.

**Pull request closed without merging**
