### PR TITLE
Add the missing import statement of scala.concurrent.Future in the re…

### PR DESCRIPTION
**Pull request by satansk**
Add the missing import statement for #1406 and hope this will be helpful.

### CODE REVIEW

**Comment by jlprat** [comment]
OK TO TEST

**Comment by jlprat** [comment]
Would it be possible to amend the commit message to make it a bit shorter and to include the issue number?

**Comment by ktoso** [comment]
LGTM, I amended the commit message - thanks!

**Comment by satansk** [comment]
@jlprat I'm sorry to forget the issue number, and thanks for @ktoso 's amendment!

**Comment by jlprat** [comment]
No worries! I also forgot myself that I could amend the commit when merging! 😄
Thanks again for contributing with the PR!

**Pull request merged**
