### PR TITLE
Cleanup imports and fix #606

### LINKED ISSUE #606: regression: current master doesn't compile against akka master
this turned up in the Scala 2.12 community build:

```
[akka-http] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/akka-http-7e987c846a164652c9cdd2faa53bb7eb0e6fb7a8/akka-http-core/src/main/scala/akka/http/impl/engine/rendering/RenderSupport.scala:18: object Context is not a member of package akka.stream.stage
[akka-http] [error] import akka.stream.stage.{ Context, GraphStage, SyncDirective, TerminationDirective }
[akka-http] [error]        ^
```

@ktoso this might have to do with https://github.com/akka/akka/pull/21919 ?

### PR DESCRIPTION
**Pull request by jrudolph**
Will fix #606.

### CODE REVIEW

**Comment by ktoso** [comment]
Oh nice, so we didn't actually use any of them just that the import was there?
LGTM :)

**Comment by jrudolph** [comment]
Yes, seems they weren't used any more but were just left-overs from a former refactoring which removed the PushPullStages.

**Comment by ktoso** [comment]
Please mark milestone of ticket when merging @jrudolph :)

**Comment by jrudolph** [comment]
Thx, good point.

**Pull request merged**
