### PR TITLE
build: update to Scala 2.13.5, 2.12.13 and scalafix 0.9.26

### PR DESCRIPTION
**Pull request by jrudolph**
Also update silencer to compatible version.

### CODE REVIEW

**Review by raboof — APPROVED** [review]
Are the things we saw in https://github.com/akka/akka-http/pull/3703#issuecomment-742594353 fixed?

**Comment by jrudolph** [comment]
> Are the things we saw in [#3703 (comment)](https://github.com/akka/akka-http/pull/3703#issuecomment-742594353) fixed?

I haven't yet completely checked. I think the sbt update might be more difficult than the Scala update. But I'll do another test.

**Comment by jrudolph** [comment]
> I haven't yet completely checked. I think the sbt update might be more difficult than the Scala update. But I'll do another test.

The separate compilation issue in headers.scala is still there with 2.13.5

**Comment by jrudolph** [comment]
> > I haven't yet completely checked. I think the sbt update might be more difficult than the Scala update. But I'll do another test.
> 
> The separate compilation issue in headers.scala is still there with 2.13.5

Just checked with 2.13.3 which has the same problem, so at least it's not a regression.

**Pull request merged**
