### PR TITLE
=htc #1905 fix mima failure in 2.11

### LINKED ISSUE #1905: 2.11 Mima failures in nightly
https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.11.11/27/console

```
[error]  * method getTimeout()scala.concurrent.duration.Duration in trait akka.http.scaladsl.TimeoutAccess is present only in current version
[error]    filter with: ProblemFilters.exclude[ReversedMissingMethodProblem]("akka.http.scaladsl.TimeoutAccess.getTimeout")
```

### PR DESCRIPTION
**Pull request by jrudolph**
Fixes #1905.

### CODE REVIEW

**Comment by ktoso** [comment]
Can we add to jenkins to run this on pr validation? Worried to miss those

**Comment by jrudolph** [comment]
Not sure it's worth the effort. Would be 3 minutes (=30%) to each PR validation.

**Comment by ktoso** [comment]
Parallelism anyone? ;-)

I do think it's scary to not have mima validate properly in pr validaiton. We'll merge things, want to ship, notice during releasing it's broken, have to revert or fix. Not a fun time...

**Comment by jlprat** [comment]
:+1: for making Travis work more than is currently doing at the moment.

**Comment by ktoso** [comment]
Done in: 

https://github.com/akka/akka-http/pull/1907/files#diff-354f30a63fb0907d4ad57269548329e3

**Comment by ktoso** [comment]
PLS BUILD

**Pull request merged**
