### PR TITLE
#2330 Added application/font-woff2 media type for WOFF File Format 2.0

### PR DESCRIPTION
**Pull request by ashishkujoy**
#2330 Added application/font-woff2 media type. Refer
 https://tools.ietf.org/html/rfc8081#page-15

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by ashishkujoy** [comment]
As per this RFC WOFF File Format 1 and 2 should be font/woff and font/woff2. As of now woff file format 1 is implemented as application/font-woff, so implemented application/font-woff2 to not break the existing contract and keep the implementation schematic.

**Comment by raboof** [comment]
Perhaps we could deprecate application/font-woff and add font/woff and font/woff2 (similar to #2320)?

**Comment by ashishkujoy** [comment]
> Perhaps we could deprecate application/font-woff and add font/woff and font/woff2 (similar to #2320)?

I created a new pull request with those change but as expected build is failing because of binary in compatibility. Refer pull request 2348

**Comment by raboof** [comment]
(superseded by #2348)

**Pull request closed without merging**
