### PR TITLE
Implement reverseProxy directive (#240)

### PR DESCRIPTION
**Pull request by kag0**
Work in progress to resolve https://github.com/akka/akka-http/issues/240
Lots of credit to https://github.com/akka/akka-http/pull/324

still need to

- [ ] implement `Via` header (how important is this actually for a first version?)
- [x] add tests
- [ ] add more magnets
- [ ] provide javadsl (how important is this for a first version?)

### CODE REVIEW

**Comment by kag0** [comment]
Is there a way to run `mimaReportBinaryIssues` locally for a specific scala version?

**Comment by raboof** [comment]
Does `sbt ++2.12.6 mimaReportBinaryIssues` do the trick?

**Comment by kag0** [comment]
Is the current binary incompatibility failure on 2.11 OK? If not, why isn't it present on 2.12, and what's the right way to fix?

**Comment by kag0** [comment]
quick bump on this.
is there still interest in getting this feature in?

**Comment by odd** [comment]
I have successfully been using this directive in my latest project, so I'm quite interested in seeing it included in a future release.

**Comment by kag0** [comment]
@odd glad to hear that. If there is any feedback you have while you're using it, definitely let me know and I'll try to integrate it here.

**Comment by Gabology** [comment]
What would be needed to get some traction on this? Would personally be very interested but for me Java DSL is a must as I don't code in Scala.

**Comment by raboof** [comment]
PLS BUILD

**Comment by mushtaq** [comment]
This is the exact thing I was looking for. Is there anything blocking this pull request. Thanks!

**Comment by kag0** [comment]
> Is the current binary incompatibility failure on 2.11 OK? If not, why isn't it present on 2.12, and what's the right way to fix?

I'm still in need of an answer to this question. Maybe a member can chime in as to whether there is anything aside from that that needs improvement.

**Comment by kag0** [comment]
@Gabology I added java support, does the api look appropriate for you?

**Comment by kag0** [comment]
@raboof I'm not sure how the java dsl directive type hierarchy works. Everything is an abstract class with `BasicDirectives` at the bottom. So should I be making `BasicDirectives extends ReverseProxyDirectives`?

**Comment by raboof** [comment]
@kag0 We recommend people to import the directives with `akka.http.scaladsl.server.Directives._` (scala) or `import static akka.http.javadsl.server.Directives.*;` (java).

The Scala `Directives` mixes in all actual directive implementations as traits [like you already found](https://github.com/akka/akka-http/pull/2020/files#diff-9ef83b15ae379f9f080ae5a1a25ab3d6R40).

Java unfortunately does not have multiple inheritance like this, so instead we create a 'chain' of implementations all extending each other. To add your directives to the 'bottom of the chain' like in Scala, extend your new API's at https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/javadsl/server/Directives.scala#L14, and have them extend the `FramedEntityStreamingDirectives` to connect to the rest of the chain.

Does that make sense?

**Comment by raboof** [comment]
(travis still catches a compile error when compiling with 2.11, btw https://travis-ci.org/akka/akka-http/builds/478845890#L639)

**Comment by kag0** [comment]
That makes sense, took care of the 2.11 issue as well.

**Comment by raboof** [comment]
Closing due to inactivity - feel free to reopen when work on this continues!

**Comment by kag0** [comment]
Looking back through here and it seems there's a lot of interest and even some SWIM using it in production. I should get back on the horse and get this merged.

Where did we leave off? Seems like things should be compiling on 2.11, we have the java api, we might feel OK ignoring the MiMa error. Anything I'm missing?

**Pull request closed without merging**
