### PR TITLE
Provide Http Model documentation for Java #761

### PR DESCRIPTION
**Pull request by jlprat**
Issue: #761
Documentation for:
* Limiting message entity lenght
* Registering Custom Media Types
* Registering custom Status Codes
* The Uri Model

Additionally, fixed some typos and wordings

### CODE REVIEW

**Comment by jlprat** [comment]
Custom Headers is missing from this PR as the full API as stated in Scala docs is missing. If you want, I will address it in a different PR.

**Comment by jlprat** [comment]
Looking at the Custom Headers documentation for Scala [custom-headers](http://doc.akka.io/docs/akka-http/current/scala/http/common/http-model.html#custom-headers) I don't think we can provide a similar highlevel API for it. And the only way to supply a Custom Header would be with extending `CustomHeader` (which BTW is discouraged in the Scala API). What do you think?

**Comment by ktoso** [comment]
What do you mean that we can't provide it? We totally can as far as I can see - what's the blocker in your opinion?

**Comment by jlprat** [comment]
I was thinking about things like:
```scala
val RawHeader(k2, v2) = ApiTokenHeader("token")
k2 should ===("apiKey")
v2 should ===("token")

val ApiTokenHeader(v3) = RawHeader("APIKEY", "token")
v3 should ===("token")
```
Mainly the last one, in Java could be quite nasty. Meaning we create a `RawHeader` but then we treat it as `ApiTokenHeader`.

Maybe I'm looking at the problem from a too close distance and I need to step back. But I don't think this is easily doable for Java without some castings.

**Comment by ktoso** [comment]
That's a niffty Scala feature which Java simply does not have in this syntax and would simply be:
`ApiTokenHeader.unapply(rawHeader): Optional<ApiTokenHeader>` in java

**Comment by jlprat** [comment]
So do we want to offer this as a feature?

**Comment by ktoso** [comment]
Yes, since I think this also is used by Http infra to create those instances from raw headers.

**Comment by jlprat** [comment]
OK, what do you think about addressing this in a separate PR, as this one is purely about docs?

**Comment by ktoso** [comment]
I'll review later today and chime in on that

**Comment by jlprat** [comment]
I'll try to find some time to work on the pending feature. I will start in a different branch, and I can merge later if needed

**Comment by jlprat** [comment]
Thanks for reviewing!

**Pull request merged**
