### PR TITLE
Ported validatePullRequest to this repo (#311).

### PR DESCRIPTION
**Pull request by rbudzko**
I think I've ported everything connected to validatePullRequest - behaved in sensible way locally :pray:. Excluded MultiNode thing.

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TES

**Comment by ktoso** [comment]
OK TO TEST

**Comment by ktoso** [comment]
My keyboard seems to slowly die on the T key :(

**Comment by rbudzko** [comment]
Better than W :suspect: !

**Comment by rbudzko** [comment]
@ktoso, a random timeout?

**Comment by ktoso** [comment]
LGTM, thanks a lot Robert :)

**Comment by ktoso** [comment]
The failure was a timing thing I fixed in my not yet merged PR

**Comment by ktoso** [comment]
resolves #311

**Pull request merged**
