### PR TITLE
Docs. Change snippet id to not start with a number

### PR DESCRIPTION
**Pull request by jlprat**
Issue: #636
Paradox doesn't seem to support snippets whose id starts with a number.
Change id format for offending ones.

### CODE REVIEW

**Comment by jrudolph** [comment]
LGTM

**Comment by jrudolph** [comment]
I wonder: did the docs build fail with the old identifiers? We should make sure that things like that are checked.

**Comment by jlprat** [comment]
Docs build was successful, I opened an issue in Paradox: https://github.com/lightbend/paradox/issues/79

**Comment by jlprat** [comment]
I was playing around with it, and it looks like, if the `id` starts with 0, the whole identifier checking (if it exists in the source file linked) is not happening at all.

**Comment by jrudolph** [comment]
Ok, thanks for th explanation.

**Comment by jlprat** [comment]
Sure thing

**Comment by ktoso** [comment]
Very weird paradox issue... thanks for noticing and reporting there.

**Pull request merged**
