### PR TITLE
=doc Doc consolidation index #1290

### PR DESCRIPTION
**Pull request by jlprat**
Refs: #1290 

Done in two commits, the first one consolidates index and move websocket page.
The second consolidates websocket page.

### CODE REVIEW

**Comment by jonas** [comment]
Isn't this similar to #1351 ?

**Comment by jlprat** [comment]
Right, I don't know why I did it, I guess I misread it

**Comment by jlprat** [comment]
Then, I leave just the first commit.

**Comment by jlprat** [comment]
To be merged after #1351

**Comment by jlprat** [comment]
I have some small comments and some change request for the `isText` methods and co. Comments are made on the commit directly:
https://github.com/akka/akka-http/commit/22fd7806a0152cb3cfb13e2c8457e936e58a18a1

**Comment by jlprat** [comment]
Ready to review

**Pull request merged**
