### PR TITLE
build: publish to sonatype directly

### PR DESCRIPTION
**Pull request by jrudolph**
That seems to work for snapshots as well.

### CODE REVIEW

**Review by andreaTP — APPROVED** [review]

**Comment by jrudolph** [comment]
Publishing still fails because we need to override `sonatypeProfileName`, however since the default is not marked a Global setting in sbt-sonatype, it seems it cannot be simply overridden (so that it will work deterministically).

**Comment by jrudolph** [comment]
I fixed the remaining issues and also adapted the release script. Let's merge this after validation and see that it at least works for snapshots. Then when we do the next release, we probably be extra cautious to see if everything still works as expected.

**Comment by ignasi35** [comment]
> I fixed the remaining issues and also adapted the release script. Let's merge this after validation and see that it at least works for snapshots.

How does it work for snapshots on Sonatype?

**Comment by ignasi35** [comment]
> > I fixed the remaining issues and also adapted the release script. Let's merge this after validation and see that it at least works for snapshots.
> 
> How does it work for snapshots on Sonatype?

I wonder if the `-SNAPSHOT` suffix is managed by `sbt-ci-release`.

**Comment by jrudolph** [comment]
> > > I fixed the remaining issues and also adapted the release script. Let's merge this after validation and see that it at least works for snapshots.
> > 
> > 
> > How does it work for snapshots on Sonatype?
> 
> I wonder if the `-SNAPSHOT` suffix is managed by `sbt-ci-release`.

I guess so, nothing had to be adjusted for that to work.

**Comment by mkurz** [comment]
The docs still point to bintray: https://github.com/akka/akka-http/blob/master/docs/src/main/paradox/contributing.md

**Pull request merged**
