### PR TITLE
10.1 backports from master

### PR DESCRIPTION
**Pull request by jrudolph**
As of 32e9a0bb1f9be69bec91cb687fdeb578a3ccd8b7 in master.

I basically `git rebase -i` master and manually removed commits that shouldn't go into 10.1.

Since there are so many, should we still break them down into single ones?

For now this is fodder for the PR validator.

### CODE REVIEW

**Comment by jrudolph** [comment]
@raboof WDYT about doing backports wholesale like this? Any better idea? We might want to add something to the commit descriptions to mark them as backported.

**Comment by raboof** [comment]
Seem fine to backport like this (without squashing on merge), since they were squashed on the original merge

**Comment by jrudolph** [comment]
Now ready for review, I squashed a few things that belonged together (subsequent version upgrades). I had to fix one commit (jackson) because it came after the scalatest 3.1.0 dep change which is not included. I first accidentally included a non-compatible change (UseHttp2 removal), so make sure you look out for those kind of things. Most of the things are test changes which can be basically ignored for this review.

FTR, here's the approximate rebase todo used:

```
# pick 4f02016c69 Drop Scala 2.11 #2589
pick d80267874a Update specs2-core to 4.8.2
pick 197b767674 Update sbt-header to 5.4.0
pick 24f9d65e7a Update scalacheck to 1.14.3
pick 14d8a8f166 Update sbt-paradox-akka to 0.29
pick 6ce12ca6a5 Update sbt-paradox-akka to 0.31 (#2969)
pick f799d1bdd1 Update jackson dependency to 2.10.2 (#2871)
pick dd83ffec09 Update reflections to 0.9.12 (#2874)
pick 1517be3c90 Update junit to 4.13
pick 84a928bb74 Update specs2-core to 4.8.3
# pick 241e7609a1 Update to Scalatest 3.1.0
# pick 50a899f775 Fix more scalatest 3.1.0 deprecations
pick 5509adff02 Update sbt to 1.3.7
s 8d8aaa8f9a Update sbt to 1.3.8
pick cc3f6b86be Update caffeine to 2.8.1
pick e73e68c2c0 Update github-api to 1.102
s c29c405dc4 Update github-api to 1.106 (#2912)
pick b6560cd6c3 Update sbt-unidoc to 0.4.3 (#2913)
pick a43b62cc0f Update sbt-mima-plugin to 0.6.4
pick 572be974de Don't automatically update Akka
pick 3f7d373285 build: always use latest for compatibility tests
pick 1d9669e756 build: cache coursier directory in travis
s 468b68868e build: cache modern coursier cache directory in travis (#2880)
pick fb9a247773 build: better diagnostics when validatePullRequest fails weirdly
pick ebfd558059 = only catch NonFatal Exceptions
pick 6bfe23d022 Potential fix for idle timeouts in http2
pick c34732e4ff http2: fix HeaderCompression updating table size without giving notice to peer
pick 04a81b6194 Add the remote address in parse errors when possible (when remote header enabled)
s b493b71c0a Include port as well
pick ea749d5348 core: silence outgoing request stream error (and make it more useful)
pick eb9ceabccc core: give more time to complete and better logging in HttpServerSpec
# pick 391e075c08 core: No more UseHttp2 (#2896)
pick faf893e14f docs: add warning on usage on extractClientIP (#2922)
pick b46e756596 Add quotes to curl request with parameters
pick e7d00b2a03 core: log more by default in MessageSpec (#2925)
pick 5af7cc8b9a Fix headers javadsl scaladoc
pick af41f9749f core: fix EntityDiscardingSpec expected error message, fixes #2929
pick 27a0bd8c39 core: use automatic port allocation in ConnectionPoolSpec, fixes #2933
pick e50ff54205 docs: fix HttpServerWithTypedSample compilation against 2.6
pick ca0a0bf05e core: remove temporaryServerHostnameAndPort in TightRequestTimeoutSpec
pick d7d9cb83e2 tests: fix log message matching in HttpAppSpec
pick cbad25ce06 test: enable WithLogCapturing for all tests deriving from RoutingSpec
pick dca1eda4d7 test: fix RouteDirectivesExamplesSpec
pick 39eb96a538 core: identify Content-Type `charset` parameter even if not lower case (#2926)
pick e066319b17 core: prevent initialization NPE which might fail all retries quickly (#2958)
pick 2f877845d0 core: remove some instances of failing `temporaryServerHostname… (#2959)
pick 75d954b687 build: add exclusion for Extension issues when building against Akka 2.6 (#2945)
pick 4e5f8f5b16 bench: add UriParser benchmarks (#2861)
pick 52a8023348 cache: try to harding ExpiringLfuCacheSpec (#2960)
pick 9925fbe4a0 test: handle test exceptions separately from regular exceptions (#2949)
pick 5950c3e0df core: introduce Inherited.upcast to fix warning in javadsl.Http (#2963)
pick a4daaee8df core: nest correctly in NewHostConnectionPool (#2964)
pick 1ef209fde6 Fix cancellation race conditions on the client-side (#2965)
pick 16cb71ceee Docs: set the correct version for project info (#2858)
pick 99028e1112 docs: show RequestBuilding in client examples (#2968)
edit 0b4d40f9d0 jackson: better JSON validation error when unmarshalling (#2901)
```

To prefix the commit messages, I used 

```sh
git filter-branch -f --msg-filter '
                 echo -n "[backport] " && cat
           ' 40b6e692756ecb04942cf82e66fcf134fc8343f0..HEAD
```

**Comment by jrudolph** [comment]
Let's go with this one!

**Comment by jrudolph** [comment]
Let's see if that fixes that the mima compilation problems in the nightlies.

**Pull request merged**
