### PR TITLE
Wip perf jenkins working

### PR DESCRIPTION
**Pull request by ktoso**
Makes https://jenkins.akka.io:8498/view/Performance/job/akka-http-perf/205/console work again

### CODE REVIEW

**Comment by ktoso** [comment]
Failure was ssh key things, hope it fixed.

**Comment by ktoso** [comment]
PLS BUILD

**Comment by ktoso** [comment]
PLS BUILD

**Comment by ktoso** [comment]
I'll merge this, we want the graphs asap :)

**Comment by jrudolph** [comment]
Great!

**Comment by jonas** [comment]
Is there a good place to put that link for posterity? The CONTRIBUTING file or maybe a new developer resources document.

**Comment by ktoso** [comment]
Contributing in a section on jenkins would be fine. I would not want people
(random people) go there and think those numbers are the max throughput we
have ;-) The jenkins boxes are really slow and serve only to see trends in
perf :)

Feel free to add contributing with such note if you want to!

-- 
Konrad Malawski

**Pull request merged**
