### PR TITLE
Update scala to 2.12.6

### PR DESCRIPTION
**Pull request by Philippus**

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks!

I'm not sure what to do about paradise hmmm...
Eugene stepped down from it but I was sure someone was going to at least release it.
We'll ask Scala Team; (@SethTisue do you know what to do about macro paradise for 2.12.16? Our parser infrastructure needs it).

```
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalamacros/paradise_2.12.6/2.1.1/paradise_2.12.6-2.1.1.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalamacros#paradise_2.12.6;2.1.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scalamacros:paradise_2.12.6:2.1.1 (Defaults.scala#L3068)
[warn] 		  +- com.typesafe.akka:akka-parsing_2.12:10.1.1+20-65d51b21 ()
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scalamacros#paradise_2.12.6;2.1.1: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
```

**Comment by SethTisue** [comment]
Adriaan is working with Eugene B to publish macro paradise for 2.12.6.

**Comment by ktoso** [comment]
Thanks a lot for the info!

**Comment by Philippus** [comment]
looks like it's been published.

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
Next stop: https://github.com/lightbend/genjavadoc/issues/138

**Comment by raboof** [comment]
Thanks for keeping track of this!

**Comment by ktoso** [comment]
(Triggered CLA checker)

**Comment by ktoso** [comment]
Rebased, will merge once validated green

**Pull request merged**
