### PR TITLE
build: try to report test results in GHA

### PR DESCRIPTION
**Pull request by jrudolph**

### CODE REVIEW

**Review by raboof — APPROVED** [review]
curious to see what this looks like ;)

**Comment by jrudolph** [comment]
Doesn't work yet, since it doesn't manage to pick up any files so far...

**Comment by jrudolph** [comment]
> Doesn't work yet, since it doesn't manage to pick up any files so far...

Ok, we didn't run any tests because ValidatePullRequest decided it's not necessary ;)

**Comment by jrudolph** [comment]
The upload seems to work after all, there just weren't any test results to pick up before... Going ahead with merging, the report workflow will only work once merged.

**Comment by jrudolph** [comment]
Here's the first result of the main build: https://github.com/akka/akka-http/runs/5108127753#r7

**Comment by raboof** [comment]
> Here's the first result of the main build: https://github.com/akka/akka-http/runs/5108127753#r7

Cool! I noticed that you can find it from https://github.com/akka/akka-http/runs/5108014106?check_suite_focus=true by chopping off `?check_suite_focus=true` (not sure if there's a neater way).

It does look like the report gets truncated though ("Report exceeded GitHub limit of 65535 bytes and has been trimmed")

**Pull request merged**
