### PR TITLE
h2 client: don't accept new streams/requests when we sent GOAWAY

### PR DESCRIPTION
**Pull request by raboof**
~On top of #3672~ (rebased)

### CODE REVIEW

**Comment by raboof** [comment]
PLS BUILD

**Comment by johanandren** [comment]
Is this PR complete or do you expect to do the `// TODO: but not accept new requests` as well?

**Comment by raboof** [comment]
> Is this PR complete or do you expect to do the `// TODO: but not accept new requests` as well?

I'm working on that scenario now, but this already seems like a self-contained improvement that could be reviewed and merged independently. I guess we should first focus on #3671 and #3672 though, I'll convert this one to draft for now.

**Comment by johanandren** [comment]
Looks good to me this far

**Comment by raboof** [comment]
> Looks good to me this far

Thanks! Extended this in #3689.

**Pull request closed without merging**
