### PR TITLE
BidiFlow backpressure test case checks if buffer has been filled up now (#423).

### PR DESCRIPTION
**Pull request by rbudzko**
It seems the test was meant to full the buffer and emit additional 8 elements. If we stall flow it should read  `0` vs `24` from counter and compare `24+8` to `0+8`.

### CODE REVIEW

**Comment by rbudzko** [comment]
Refs #423.

**Comment by jrudolph** [comment]
OK TO TEST

**Comment by jrudolph** [comment]
This test case has been pestering us for quite some time. Thanks, @rbudzko, for looking into it. I made a slight simplification and added a lot more comments to the test.

WDYT, @rbudzko?

**Comment by rbudzko** [comment]
@jrudolph LGTM :shipit:

**Comment by rbudzko** [comment]
`ConnectionPoolSpec` - I'll create an issue...

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
Failed: https://github.com/akka/akka-http/issues/492

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by rbudzko** [comment]
My PRs always look like a bloodbath 👿 .

**Comment by jrudolph** [comment]
Hehe, not your fault ;)

**Comment by jrudolph** [comment]
(Sorry, I failed this one.)

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
Great. Thanks again, @rbudzko.

**Pull request merged**
