### PR TITLE
[docs] Add missing import `akka.actor.ActorSystem`

### PR DESCRIPTION
**Pull request by jtwarren**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @jtwarren,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jrudolph** [comment]
OK TO TEST

**Comment by jrudolph** [comment]
Thanks, @jtwarren. Yes, I agree it makes sense to include all necessary imports directly in these introductory examples. If you'd like could you also change the other imports to be included manually? If you delete all (not testing relating) imports from the top of the file, you will see which example needs additional explicit imports.

**Comment by ktoso** [comment]
LGTM, thanks - it would be nice to improve the imports even a bit more, would you be able to do that in a follow-up PR? Thanks a lot in advance!

**Comment by ktoso** [comment]
Proposing to make the additional changes a follow-up to keep the PR queue small.

**Pull request merged**
