### PR TITLE
fix typo in docs

### PR DESCRIPTION
**Pull request by EnverOsmanov**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @EnverOsmanov,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
Nice thanks! Still need the CLA to be signed though before we can merge. :)

**Comment by EnverOsmanov** [comment]
@ktoso I just signed it (I think).

**Comment by ktoso** [comment]
Thanks a lot, yeah it's just the via github confirmation :) Thanks!

**Pull request merged**
