### PR TITLE
Fall through on AssertionErrors in testkit (#3400)

### PR DESCRIPTION
**Pull request by ArturSoler**
References #3400 

Covering both ScalaTest and Specs2

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @ArturSoler,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by ignasi35** [comment]
OK TO TEST

**Review by ignasi35 — APPROVED** [review]
LGTM.

**Comment by ignasi35** [comment]
Thanks @ArturSoler and congrats on your first contrib! :-)

**Review by raboof — APPROVED** [review]
This makes sense to me!

In the unlikely scenario that someone'd like to use AssertionError in their actual routes and test that, they can provide their own exceptionhandler.

**Pull request merged**
