### PR TITLE
HttpCookie.copy was calling itself recursively

### PR DESCRIPTION
**Pull request by rleibman**
References #3669

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by rleibman** [comment]
Incidentally... this fixed my issue when using akka-http-session

**Review by raboof — APPROVED** [review]
Oops! Thanks!

**Review by ignasi35 — APPROVED** [review]
👍🏼

**Comment by jrudolph** [comment]
Have you checked if 10.1 is also affected? If yes, we should backport.

**Pull request merged**
