### PR TITLE
Enable HTTP/2 chunked responses #2217

### PR DESCRIPTION
**Pull request by ctoomey**
Refs. #2217

### CODE REVIEW

**Comment by johanandren** [comment]
Refs #2217

**Comment by raboof** [comment]
OK TO TEST

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
> Does it really end up as 'chunked' on the wire (which would be wrong) or do we ignore the fact that it was presented as 'chunked' and stream it like a regular entity (which might be OK, but perhaps would warrant a test?)?

`Transfer-Encoding` doesn't really make sense for HTTP/2 as it defines it's own stream transport protocol. Instead, we (ab)use our model for `Chunked` entities to support trailers in HTTP/2 (#1857).

**Comment by ctoomey** [comment]
Will you guys please merge this so it'll be in the next release?

Also it's not super clear to me from the discussion above -- are you saying the akka-grpc response generation is HTTP/2 conformant because though it uses chunking, it doesn't use the chunked transfer encoding which is the thing that's verboten?

**Comment by jrudolph** [comment]
> are you saying the akka-grpc response generation is HTTP/2 conformant 

Yes, it uses the akka-http2-support implementation in a valid way.

> because though it uses chunking, 

It uses `HttpEntity.Chunked` which in akka-http's HTTP/2 implementation is interpreted differently than for HTTP/1.1.

> it doesn't use the chunked transfer encoding which is the thing that's verboten?

Exactly. akka-http2-support will translate `HttpEntity.Chunked` to regular HTTP/2 streams but ignores some part of the model (namely the `extension` field of `ChunkStreamPart`).

**Comment by jrudolph** [comment]
Btw. it already works now in akka-grpc because you don't have to set a matching protocol for `HttpResponse`.

**Comment by raboof** [comment]
Failure is #2108

**Comment by raboof** [comment]
PLS BUILD

**Pull request merged**
