### PR TITLE
Both assertHeaderExists functions now behave in the same way.

### PR DESCRIPTION
**Pull request by rbudzko**
While not sure if it is a desired behavior, I'd like to propose such a change :innocent: .

### CODE REVIEW

**Comment by rbudzko** [comment]
BTW, it's #5.

**Comment by ktoso** [comment]
This does not solve #5 though? I was about making the error message show what headers were available in addition to saying what was missing.

**Comment by ktoso** [comment]
OK TO TES

**Comment by ktoso** [comment]
OK TO TEST

**Comment by rbudzko** [comment]
> This does not solve #5 though? I was about making the error message show what headers were available in addition to saying what was missing.

Another `assertHeaderExists` (called inside) is stating that header was missing or that it was present but none of given values was compliant with the assertion: `header was found but had the wrong value. Found headers: ${headers.mkString(", ")}")`.

**Comment by ktoso** [comment]
Please mention such things in PRs ;) It's non obvious to see from the changes made that now it's supposed to work as intended

**Comment by ktoso** [comment]
LGTM

**Comment by rbudzko** [comment]
> Please mention such things in PRs ;) It's non obvious to see from the changes made that now it's supposed to work as intended

Uh, sorry. Will do in future.

**Comment by jypma** [comment]
Thanks for the PR! Even more important than the PR text is the commit message. If it resolves #5, mention it in the message. And be specific: rather than saying "in the same way", explain what that way is.

That way, anyone browsing the code at a future point in time can immediately see the intentions, without having to do further digging.

**Comment by rbudzko** [comment]
Thanks for the feedback! I've improved the commit message.

**Comment by jypma** [comment]
```
[info]   - the config setting (chunked entity) *** FAILED ***
[info]     null did not equal EntityStreamSizeException: actual entity size (None) exceeded content length limit (10 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.,
[info]     inside HttpResponse(200 OK,List(),HttpEntity.Chunked(application/octet-stream),HttpProtocol(HTTP/1.1)) (LowLevelOutgoingConnectionSpec.scala:564)
```
is that even related to the change?

**Comment by jrudolph** [comment]
> @akka/akka-http-team Do we have a policy re. commit msgs yet?

I'd say we try to keep the akka one for consistency.

**Comment by 2beaucoup** [comment]
Thx @rbudzko!

**Comment by 2beaucoup** [comment]
> I'd say we try to keep the akka one for consistency.

see https://github.com/akka/akka-meta/issues/30

**Pull request merged**
