### PR TITLE
Update Scala to 2.12.9

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by raboof** [comment]
Fails on mima. Some of these need a MiMa update (#2656), but some others remain to be investigated.

**Comment by raboof** [comment]
For example, it seems with 2.12.8, the first, synthetic parameter of `GracefulTerminatorStage.ConnectionTerminator` is part of the descriptor and of the Signature.

With 2.12.9, it is still part of the descriptor but now dropped from the Signature.

2.12.8:
```
  public akka.http.impl.engine.server.GracefulTerminatorStage$ConnectionTerminator(akka.http.impl.engine.server.GracefulTerminatorStage, scala.concurrent.Promise<scala.Function1<scala.concurrent.duration.FiniteDuration, scala.concurrent.Future<akka.http.scaladsl.Http$HttpTerminated>>>);
    descriptor: (Lakka/http/impl/engine/server/GracefulTerminatorStage;Lscala/concurrent/Promise;)V
    flags: ACC_PUBLIC
    Code:
      stack=2, locals=3, args_size=3
         0: aload_0
         1: aload_2
         2: putfield      #28                 // Field triggerTermination:Lscala/concurrent/Promise;
         5: aload_0
         6: invokespecial #82                 // Method akka/http/impl/engine/server/ServerTerminator."<init>":()V
         9: return
      LineNumberTable:
        line 178: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      10     0  this   Lakka/http/impl/engine/server/GracefulTerminatorStage$ConnectionTerminator;
            0      10     1 $outer   Lakka/http/impl/engine/server/GracefulTerminatorStage;
            0      10     2 triggerTermination   Lscala/concurrent/Promise;
    Signature: #78                          // (Lakka/http/impl/engine/server/GracefulTerminatorStage;Lscala/concurrent/Promise<Lscala/Function1<Lscala/concurrent/duration/FiniteDuration;Lscala/concurrent/Future<Lakka/http/scaladsl/Http$HttpTerminated;>;>;>;)V
    MethodParameters:
      Name                           Flags
      $outer                         final synthetic
      triggerTermination             final
}
```

2.12.9:
```
  public akka.http.impl.engine.server.GracefulTerminatorStage$ConnectionTerminator(scala.concurrent.Promise<scala.Function1<scala.concurrent.duration.FiniteDuration, scala.concurrent.Future<akka.http.scaladsl.Http$HttpTerminated>>>);
    descriptor: (Lakka/http/impl/engine/server/GracefulTerminatorStage;Lscala/concurrent/Promise;)V
    flags: ACC_PUBLIC
    Code:
      stack=2, locals=3, args_size=3
         0: aload_0
         1: aload_2
         2: putfield      #28                 // Field triggerTermination:Lscala/concurrent/Promise;
         5: aload_0
         6: invokespecial #82                 // Method akka/http/impl/engine/server/ServerTerminator."<init>":()V
         9: return
      LineNumberTable:
        line 178: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      10     0  this   Lakka/http/impl/engine/server/GracefulTerminatorStage$ConnectionTerminator;
            0      10     1 $outer   Lakka/http/impl/engine/server/GracefulTerminatorStage;
            0      10     2 triggerTermination   Lscala/concurrent/Promise;
    Signature: #78                          // (Lscala/concurrent/Promise<Lscala/Function1<Lscala/concurrent/duration/FiniteDuration;Lscala/concurrent/Future<Lakka/http/scaladsl/Http$HttpTerminated;>;>;>;)V
    MethodParameters:
      Name                           Flags
      $outer                         final synthetic
      triggerTermination             final
}
```

https://docs.oracle.com/javase/specs/jvms/se12/html/jvms-4.html#jvms-4.7.9 says:

> A method signature encoded by the Signature attribute may not correspond exactly to the method descriptor in the method_info structure (§4.3.3). In particular, there is no assurance that the number of formal parameter types in the method signature is the same as the number of parameter descriptors in the method descriptor. The numbers are the same for most methods, but certain constructors in the Java programming language have an implicitly declared parameter which a compiler represents with a parameter descriptor but may omit from the method signature.

... so this is perhaps intentional.

**Comment by raboof** [comment]
(fixed in https://github.com/lightbend/mima/pull/378)

**Comment by raboof** [comment]
(now just needs #2656 I think)

**Comment by jrudolph** [comment]
Can you rebase on master to trigger a recheck with the mima updates in?

**Comment by raboof** [comment]
willdo

**Pull request merged**
