### PR TITLE
=doc Fix path matcher doc page

### PR DESCRIPTION
**Pull request by jlprat**
Page has dangling `@@@`. Remove top text stating that this only makes sense for Scala DSL.

### CODE REVIEW

**Comment by jrudolph** [comment]
Thanks, @jlprat. While you are at it, could you fix two additional things:

 * The Java version of https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/path-directives/index.html is missing a link to the PathMatcher DSL
 * It seems the PathMatcher DSL page isn't linked in any TOC? I think we should place it nested in "Routing DSL" just below "Directives"

**Comment by ktoso** [comment]
LGTM, hope you can pick up the other suggestions into this PR @jlprat ? :)

**Comment by jlprat** [comment]
Hi, yes I can pick them up, later today :)

**Comment by jlprat** [comment]
Feedback @jrudolph: The link under https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/path-directives/index.html will automatically appear when this PR is merged (something about Paradox not adding a title if there is no headline). At least is what it happens on my local build :)

I'll add the second point in a couple of hours

**Comment by jlprat** [comment]
The link under Routing DSL is already there (after exception handling), but not rendered because it's already part of another TOC (Path directives). AFAIK this is a paradox feature. Any ideas? Or should I leave it as it is?

**Comment by jrudolph** [comment]
I see, I think then it's fine for now.

**Comment by jlprat** [comment]
Shall I merge then?

**Comment by jrudolph** [comment]
Yep, please go ahead :)

**Pull request merged**
