### PR TITLE
h2spec compliance - size check added to PingFrame (#245)

### PR DESCRIPTION
**Pull request by gosubpl**
Fixes h2spec suites: 6.7

Size checks added to:
* PingFrame

StreamId checks added to:
* PingFrame

### CODE REVIEW

**Comment by ktoso** [comment]
Is it do-not-merge still?

**Comment by gosubpl** [comment]
@ktoso thanks for reviewing. I plan to add some more 'low hanging fruit' in the evening today. Will ping when ready for merge.

**Comment by ktoso** [comment]
I certainly don't mind multiple small PRs by the way ;-)

**Comment by gosubpl** [comment]
@ktoso glad that you don't mind. Then this is ready for merge.

**Comment by ktoso** [comment]
Excellent, thanks

**Comment by gosubpl** [comment]
Thanks!

**Pull request merged**
