### PR TITLE
Set default connection-pool to 'new'

### PR DESCRIPTION
**Pull request by raboof**
ConnectionPoolSpec is already/still ran for both

### CODE REVIEW

**Comment by raboof** [comment]
PLS BUILD

**Comment by raboof** [comment]
Can reproduce:
selection_275

**Comment by jrudolph** [comment]
PLS BUILD

**Comment by jrudolph** [comment]
Rebased on top of latest version of #1661.

**Comment by jrudolph** [comment]
Rebased once again after merging #1661.

**Comment by jrudolph** [comment]
All tests passing ;)

Let's go ahead!

**Comment by ktoso** [comment]
Looking forward to it!
👍 :shipit:

**Pull request merged**
