### PR TITLE
Revert "[10.1 backport] server-side streamCancellationDelay"

### LINKED ISSUE #2532: akka.http.scaladsl.ClientServerSpec.The low-level HTTP infrastructure should complete a request/response over https when request has `Connection: close` set failing on 2.13
https://jenkins.akka.io:8498/job/akka-http-nightly/487/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.0-RC1,jdk=AdoptOpenJDK%208/testReport/junit/akka.http.scaladsl/ClientServerSpec/The_low_level_HTTP_infrastructure_should_complete_a_request_response_over_https_when_request_has__Connection__close__set/

```
Error Message

timeout (3 seconds) waiting for 1 messages on WarningFilter(None,Right(Hostname verification failed),false)

Stacktrace

java.lang.AssertionError: timeout (3 seconds) waiting for 1 messages on WarningFilter(None,Right(Hostname verification failed),false)
	at akka.testkit.EventFilter.intercept(TestEventListener.scala:119)
	at akka.http.scaladsl.ClientServerSpec.$anonfun$new$62(ClientServerSpec.scala:611)
	at akka.stream.testkit.scaladsl.StreamTestKit$.assertAllStagesStopped(StreamTestKit.scala:32)
	at akka.stream.testkit.Utils$.assertAllStagesStopped(Utils.scala:24)
	at akka.http.scaladsl.ClientServerSpec.$anonfun$new$61(ClientServerSpec.scala:588)
```

### PR DESCRIPTION
**Pull request by jrudolph**
Reverts the server cancellation fix backport in #3258 and fixes #2532 (broken lingerTimeout) for 10.1.x.

This reverts the cancellation behavior back to the one in 10.1.12. There was some concerns whether we should actually should do the backport and I guess after all we shouldn't have done it, so let's take the opportunity and revert it while we can.

### CODE REVIEW

**Comment by jrudolph** [comment]
I guess we might seen some flaky tests after that like the one introduced in #3288. This late in the release cycle we need to consider if actually fixing the tests makes sense or if we just disable them.

**Review by raboof — APPROVED** [review]
I agree

**Review by raboof — APPROVED** [review]
I agree

**Comment by jrudolph** [comment]
> [error] Failed tests:
> [error] 	akka.http.impl.engine.ws.WebSocketIntegrationSpec

That's the one added in #3288, so added a commit to revert that one as well.

**Comment by jrudolph** [comment]
> That's the one added in #3288, so added a commit to revert that one as well.

Eh, yes, I did but to the wrong PR :roll_eyes:

**Pull request merged**
