### PR TITLE
Avoid jgit, replace with git commandline invocation

### PR DESCRIPTION
**Pull request by raboof**
Makes 'git worktree' work

### CODE REVIEW

**Comment by jrudolph** [comment]
> Makes 'git worktree' work

What does sbt-dynver use? Will that also work with worktree?

**Comment by jrudolph** [comment]
> I guess let's merge and monitor the master build to see if it updates the right project?

https://travis-ci.org/github/akka/akka-http/jobs/675230818

**Comment by jrudolph** [comment]
Seems to have worked.

**Comment by raboof** [comment]
> What does sbt-dynver use? 

Also the cmdline git, https://github.com/dwijnand/sbt-dynver/blob/master/src/main/scala/sbtdynver/DynVerPlugin.scala#L226

**Comment by jrudolph** [comment]
> Also the cmdline git, [dwijnand/sbt-dynver:src/main/scala/sbtdynver/DynVerPlugin.scala@`master`#L226](https://github.com/dwijnand/sbt-dynver/blob/master/src/main/scala/sbtdynver/DynVerPlugin.scala#L226) [](/dwijnand/sbt-dynver/blob/HEAD@{2020-04-15T10:54:04Z}/src/main/scala/sbtdynver/DynVerPlugin.scala#L226)

Thanks, good!

**Pull request merged**
