### PR TITLE
Minor correction in rejections.md

### PR DESCRIPTION
**Pull request by fedeoasi**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @fedeoasi,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jrudolph** [comment]
OK TO TEST

**Comment by ktoso** [comment]
Hi @fedeoasi, this looks good -- we need the CLA to be signed before we can merge though;

**Comment by lightbend-cla-validator** [comment]
Hi @fedeoasi,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ktoso** [comment]
Thanks

**Pull request merged**
