### PR TITLE
Release notes for 10.0.3 (and stubs for previous versions)

### PR DESCRIPTION
**Pull request by jrudolph**

### CODE REVIEW

**Comment by jrudolph** [comment]
Thanks, @ktoso good point. We can either retag or just fix the version before pushing the docs.

**Comment by ktoso** [comment]
retag is fine here IMO

**Comment by jonas** [comment]
This is great. I would suggest a more consistent use of capital letters to start each entry.

@ktoso You can alway build the docs forcing a specific version with something like:

    sbt 'project docs' 'set version in paradox := "10.0.3" paradox

**Comment by ktoso** [comment]
thats lying about what they are though. Next time someone runs thigns you suddenly did wrong docs (missing pages). Builds must be repeatable.

**Comment by jrudolph** [comment]
@jonas regarding capital letters, you mean the bullet points, right? Will do.

**Comment by jonas** [comment]
@jrudolph Yes, the bullet points randomly start with or without capital letter. We should pick one way. ;)

**Comment by jrudolph** [comment]
Yes, absolutely. I started with the log lines from the commits and then forget to go over it again.

**Comment by jrudolph** [comment]
Forgot to push the capital letters which I now pushed to master directly.

**Comment by ktoso** [comment]
ok ;)

**Pull request merged**
