### PR TITLE
Added support for Matching empty string on empty string matching regex #1010

### LINKED ISSUE #1010: Regex PathMatcher should match on empty segment if empty string matches regex
When using a regex that is matched by the empty string, `akka.http.scaladsl.server.PathMatcher._regex2PathMatcher` fails to match on it

    import akka.http.scaladsl.server.{PathMatcher, PathMatcher1}
    import PathMatcher._
    import akka.http.scaladsl.model.Uri.Path

    val regex = "a*".r
    val matcher: PathMatcher1[String] = regex

    assert(regex.findFirstIn("a") == Some("a"))
    assert(regex.findFirstIn("") == Some(""))

    assert(matcher("a" :: Path.Empty) == Matched(Path.Empty, Tuple1("a")))
    assert(matcher("" :: Path.Empty) == Matched(Path.Empty, Tuple1("")))  //AssertionError

### PR DESCRIPTION
**Pull request by domitian**
Fixes #1010 . This is my first contribution here, signed the CLA.

### CODE REVIEW

**Comment by jlprat** [comment]
Welcome, and thanks for contributing!

**Comment by domitian** [comment]
@jlprat thanks, I am relatively new to the scala ecosystem as well. I am still getting used to it, come from ruby world. I need small help. What configuration options/commands should I run on sbt console to make all the tests pass on the local machine. Because I see some errors like 'java.lang.OutOfMemoryError: Metaspace' or concurrency related warnings.

**Comment by jlprat** [comment]
Hi, yes Akka projects consume quite some memory, you can increase it like this:
```
sbt -mem 2048 
```
Or to persist it via env variables:
```
SBT_OPTS=-Xmx2G
```

Then to run the test you can give the sbt task `validatePullRequest` a try. It will try to run the tests of the affected sub projects.

**Comment by jlprat** [comment]
Ah, and some tests are flaky and they fail from time to time.

**Comment by domitian** [comment]
Thanks, as for the pull request, are the changes enough or are any other changes necessary?

**Comment by jlprat** [comment]
We will review the PR as soon as we can. And as soon the PR is approved by 2 people it will be merged. ☺

cc @jrudolph you might want to take a look at this one.

**Comment by jrudolph** [comment]
I added a slight improvement that caches the (always equal) return value and also caches whether the regex can match the empty string. WDYT?

**Comment by domitian** [comment]
This looks more DRY, thanks @jrudolph LGTM

**Comment by jrudolph** [comment]
Great, thanks a lot @domitian.

**Pull request merged**
