### PR TITLE
[WIP] Migration to JUnit 5 + upgrade h2specVersion spec

### PR DESCRIPTION
**Pull request by golem131**

### CODE REVIEW

**Comment by raboof** [comment]
OK TO TEST

**Comment by golem131** [comment]
@raboof pls, run tests again

**Comment by jrudolph** [comment]
I wonder if moving to JUnit 5 is common enough in the Java universe to warrant this change already now?

**Comment by ktoso** [comment]
I think there's some compatibility drama going on with junit 5, please carefully review before merging. It could have large impact AFAICS

**Comment by jrudolph** [comment]
Yes, that's why I'm not sure if it's worth the effort right now.

**Comment by golem131** [comment]
@ktoso @jrudolph so what, i just close this PR?

**Comment by ktoso** [comment]
Yes I propose to make it a ticket for now and we'll track junit movements and figure out a way forward.
Please feel free to help us on that front though!

What we're looking to understand is: how's the adoption? will this break our users (I guess so)? etc

**Comment by ktoso** [comment]
Closing for now.

**Comment by golem131** [comment]
@ktoso if we provide org.junit.vintage through dependency ("JUnit Vintage test engine implementation that allows to run vintage JUnit tests, i.e. tests written in the JUnit 3 or JUnit 4 style, on the new JUnit Platform." (c) http://junit.org/junit5/docs/current/user-guide/#dependency-metadata-junit-vintage)
maybe it would be easy upgrade?

**Comment by ktoso** [comment]
Hm perhaps indeed, could you open a ticket and put that and other thoughts there so we can make a decision there and reopen the PR then? :)

**Comment by golem131** [comment]
@ktoso #1476

**Pull request closed without merging**
