### PR TITLE
Remove duplicate entries in plugins.sbt

### PR DESCRIPTION
**Pull request by witi83**
sbt-dependency-graph was defined twice.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @witi83,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jonas** [comment]
Thanks you for the patch. Would you mind also removing the duplicate entries for sbt-unidoc and sbt-boilerplate?

**Comment by witi83** [comment]
@jonas Done.

**Comment by jonas** [comment]
OK TO TEST

**Comment by jonas** [comment]
Thank you for making this clean up.

**Comment by ktoso** [comment]
Thanks :)

**Pull request merged**
