### PR TITLE
Add final boundary for multipart entities with no parts #1257

### PR DESCRIPTION
**Pull request by arnohaase**

### CODE REVIEW

**Comment by ktoso** [comment]
OK TO TEST

**Comment by arnohaase** [comment]
I signed the Lightbend CLA,

**Comment by jrudolph** [comment]
Hi, @arnohaase, thanks for the contribution.

The change seems reasonable, though it is unclear to me if multipart entities without any part would (or should) be allowed at all? Do have any reference for that?

**Comment by arnohaase** [comment]
The spec does not specifically forbid it, at least as far as I can see. But it does specify that the final boundary must always be present. https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

The problem appeared in a real-world problem where a multipart response was used to represent documents matching a search, with no parts being a valid response document.

MultipartUnmarshallers.defaultMultipartGeneralUnmarshaller can handle Multipart entities without entries  already, provided the final boundary is present.

**Comment by jrudolph** [comment]
@arnohaase 

> The spec does not specifically forbid it, at least as far as I can see.

It says:

> In the case of multiple part messages, in which one or more different sets of data are combined in a single body

I understand it that "one or more" wouldn't include zero. But I guess that's only a nitpick.

I agree we should do it consistently for marshallers and unmarshallers and also for strict and streamed. Would be nice to have tests being run for strict and streamed variants. Is that something you would like to work on, @arnohaase or @raboof?

**Comment by raboof** [comment]
@jrudolph I think that'd be interesting but am not planning to do it right now - perhaps we should merge this and keep that idea for later? Created https://github.com/akka/akka-http/issues/1309 to track it.

**Comment by jrudolph** [comment]
Yep, sounds good.

**Pull request merged**
