### PR TITLE
Moved exception handler code in example

### PR DESCRIPTION
**Pull request by olofwalker**
- Moved the code inside the MyApp object, it compiles fine with Paradox due to encapsulating object, but looks broken in the docs.

### CODE REVIEW

**Comment by raboof** [comment]
Related to #1441

**Comment by jrudolph** [comment]
OK TO TEST

**Comment by raboof** [comment]
hmm
```
[error] /localhome/jenkinsakka/workspace/pr-validator-akka-http/docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala:82: value myExceptionHandler is not a member of object docs.http.scaladsl.server.MyExplicitExceptionHandler
[error]     Get() ~> handleExceptions(MyExplicitExceptionHandler.myExceptionHandler) {
[error]                                                          ^
[error] /localhome/jenkinsakka/workspace/pr-validator-akka-http/docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala:91: value myExceptionHandler is not a member of object docs.http.scaladsl.server.MyImplicitExceptionHandler
[error]     import MyImplicitExceptionHandler.myExceptionHandler
```

**Comment by olofwalker** [comment]
Fixed it and pushed the changes

**Comment by FlorianCassayre** [comment]
[Some examples](https://github.com/akka/akka-http/blob/main/docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala#L24) are broken again.

**Comment by jrudolph** [comment]
> [Some examples](https://github.com/akka/akka-http/blob/main/docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala?rgh-link-date=2021-12-12T07%3A11%3A30Z#L24) are broken again.

What do you mean? Missing imports for compilation or broken behavior when run?

**Comment by FlorianCassayre** [comment]
> > [Some examples](https://github.com/akka/akka-http/blob/main/docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala?rgh-link-date=2021-12-12T07%3A11%3A30Z#L24) are broken again.
> 
> What do you mean? Missing imports for compilation or broken behavior when run?

The example doesn't compile.
The problem that was addressed in this PR needs to be addressed again in the same way. Essentially `myExceptionHandler` cannot be a top-level entity with respect to a file (in Scala 2), it should be in `MyApp`. The specification compiles because this snippet is itself in `MyExplicitExceptionHandler`, but a user looking at the documentation is unlikely to figure that out.

**Comment by jrudolph** [comment]
Thanks, @FlorianCassayre, created #3971 to track this. Maybe you are up for a PR?

**Comment by FlorianCassayre** [comment]
Thanks! Sure, I can do that.

**Pull request merged**
