### PR TITLE
Helper to expect a parsed frame of a given type

### PR DESCRIPTION
**Pull request by raboof**
Probably conflicts with a number of in-flight PR's, I'm happy to resolve
conflicts here.

### CODE REVIEW

**Review by jrudolph — APPROVED** [review]
LGTM

**Comment by raboof** [comment]
(failure is #3582 )

**Comment by jrudolph** [comment]
PLS BUILD

**Review by ignasi35 — APPROVED** [review]
Nice!
What's your plans about rewriting existing `expectABC_FRAME()` methods based on this new one?

**Comment by raboof** [comment]
> What's your plans about rewriting existing expectABC_FRAME() methods based on this new one?

I don't have such plans right now ;)

**Comment by ignasi35** [comment]
> I don't have such plans right now ;)

Not sure if you are answering my question or summarising the "2020 mood"™️ .

**Pull request merged**
