### PR TITLE
add [openjdk11] to Travis build matrix

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by johanandren** [comment]
OK TO TEST

**Comment by jrudolph** [comment]
The reason for the failure is https://github.com/akka/akka/issues/25784 which will be fixed in Akka 2.5.18.

**Comment by jrudolph** [comment]
Restarted the failed Travis openjdk11 build after merging #2312.

**Comment by jrudolph** [comment]
This currently doesn't work. We don't want to run tests on Travis which happens if we add more configurations to the Travis build matrix.

Instead, we are going to setup an akka-http JDK11 nightly build.

Thanks anyway, @sullis.

**Pull request closed without merging**
